/*
 * Copyright (c) 2017.
 * Distributed under the GNU GPLv3 by David Whitman.
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This source code is made available to help others learn. Please don't clone my app.
 */

package com.thunderclouddev.persistence

import com.thunderclouddev.utils.empty


/**
 * Created by david on 4/15/17.
 */
class Permission(val name: String) {
    val description by lazy {
        permissionsMap.getOrDefault(name.split(".").last().toUpperCase(), String.empty)
    }

    override fun toString() = name

    companion object {
        /**
         * Last updated from https://developer.android.com/reference/android/Manifest.permission.html
         * on 2017-04-15.
         */
        val permissionsMap = mapOf(
                "USE_CREDENTIALS" to "Allows the app to request authentication tokens.",
                "ACCESS_CHECKIN_PROPERTIES" to "Allows read/write access to the \"properties\" table in the checkin database, to change values that get uploaded.",
                "ACCESS_COARSE_LOCATION" to "Allows an app to access approximate location.",
                "ACCESS_FINE_LOCATION" to "Allows an app to access precise location.",
                "ACCESS_LOCATION_EXTRA_COMMANDS" to "Allows an application to access extra location provider commands.",
                "ACCESS_NETWORK_STATE" to "Allows applications to access information about networks.",
                "ACCESS_NOTIFICATION_POLICY" to "Marker permission for applications that wish to access notification policy.",
                "ACCESS_WIFI_STATE" to "Allows applications to access information about Wi-Fi networks.",
                "ACCOUNT_MANAGER" to "Allows applications to call into AccountAuthenticators.",
                "ADD_VOICEMAIL" to "Allows an application to add voicemails into the system.",
                "ALLOCATE_AGGRESSIVE" to "Allows an application to aggressively allocate disk space.",
                "BATTERY_STATS" to "Allows an application to collect battery statistics",
                "BIND_ACCESSIBILITY_SERVICE" to "Must be required by an AccessibilityService, to ensure that only the system can bind to it.",
                "BIND_APPWIDGET" to "Allows an application to tell the AppWidget service which application can access AppWidget's data.",
                "BIND_AUTO_FILL" to "Must be required by a AutoFillService, to ensure that only the system can bind to it.",
                "BIND_CARRIER_MESSAGING_SERVICE" to "This constant was deprecated in API level 23. Use BIND_CARRIER_SERVICES instead",
                "BIND_CARRIER_SERVICES" to "The system process that is allowed to bind to services in carrier apps will have this permission.",
                "BIND_CHOOSER_TARGET_SERVICE" to "Must be required by a ChooserTargetService, to ensure that only the system can bind to it.",
                "BIND_CONDITION_PROVIDER_SERVICE" to "Must be required by a ConditionProviderService, to ensure that only the system can bind to it.",
                "BIND_DEVICE_ADMIN" to "Must be required by device administration receiver, to ensure that only the system can interact with it.",
                "BIND_DREAM_SERVICE" to "Must be required by an DreamService, to ensure that only the system can bind to it.",
                "BIND_INCALL_SERVICE" to "Must be required by a InCallService, to ensure that only the system can bind to it.",
                "BIND_INPUT_METHOD" to "Must be required by an InputMethodService, to ensure that only the system can bind to it.",
                "BIND_MIDI_DEVICE_SERVICE" to "Must be required by an MidiDeviceService, to ensure that only the system can bind to it.",
                "BIND_NFC_SERVICE" to "Must be required by a HostApduService or OffHostApduService to ensure that only the system can bind to it.",
                "BIND_NOTIFICATION_LISTENER_SERVICE" to "Must be required by an NotificationListenerService, to ensure that only the system can bind to it.",
                "BIND_PRINT_SERVICE" to "Must be required by a PrintService, to ensure that only the system can bind to it.",
                "BIND_QUICK_SETTINGS_TILE" to "Allows an application to bind to third party quick settings tiles.",
                "BIND_REMOTEVIEWS" to "Must be required by a RemoteViewsService, to ensure that only the system can bind to it.",
                "BIND_SCREENING_SERVICE" to "Must be required by a CallScreeningService, to ensure that only the system can bind to it.",
                "BIND_TELECOM_CONNECTION_SERVICE" to "Must be required by a ConnectionService, to ensure that only the system can bind to it.",
                "BIND_TEXT_SERVICE" to "Must be required by a TextService (e.g.",
                "BIND_TV_INPUT" to "Must be required by a TvInputService to ensure that only the system can bind to it.",
                "BIND_VISUAL_VOICEMAIL_SERVICE" to "Must be required by a link VisualVoicemailService to ensure that only the system can bind to it.",
                "BIND_VOICE_INTERACTION" to "Must be required by a VoiceInteractionService, to ensure that only the system can bind to it.",
                "BIND_VPN_SERVICE" to "Must be required by a VpnService, to ensure that only the system can bind to it.",
                "BIND_VR_LISTENER_SERVICE" to "Must be required by an VrListenerService, to ensure that only the system can bind to it.",
                "BIND_WALLPAPER" to "Must be required by a WallpaperService, to ensure that only the system can bind to it.",
                "BLUETOOTH" to "Allows applications to connect to paired bluetooth devices.",
                "BLUETOOTH_ADMIN" to "Allows applications to discover and pair bluetooth devices.",
                "BLUETOOTH_PRIVILEGED" to "Allows applications to pair bluetooth devices without user interaction, and to allow or disallow phonebook access or message access.",
                "BODY_SENSORS" to "Allows an application to access data from sensors that the user uses to measure what is happening inside his/her body, such as heart rate.",
                "BROADCAST_PACKAGE_REMOVED" to "Allows an application to broadcast a notification that an application package has been removed.",
                "BROADCAST_SMS" to "Allows an application to broadcast an SMS receipt notification.",
                "BROADCAST_STICKY" to "Allows an application to broadcast sticky intents.",
                "BROADCAST_WAP_PUSH" to "Allows an application to broadcast a WAP PUSH receipt notification.",
                "CALL_PHONE" to "Allows an application to initiate a phone call without going through the Dialer user interface for the user to confirm the call.",
                "CALL_PRIVILEGED" to "Allows an application to call any phone number, including emergency numbers, without going through the Dialer user interface for the user to confirm the call being placed.",
                "CAMERA" to "Required to be able to access the camera device.",
                "CAPTURE_AUDIO_OUTPUT" to "Allows an application to capture audio output.",
                "CAPTURE_SECURE_VIDEO_OUTPUT" to "Allows an application to capture secure video output.",
                "CAPTURE_VIDEO_OUTPUT" to "Allows an application to capture video output.",
                "CHANGE_COMPONENT_ENABLED_STATE" to "Allows an application to change whether an application component (other than its own) is enabled or not.",
                "CHANGE_CONFIGURATION" to "Allows an application to modify the current configuration, such as locale.",
                "CHANGE_NETWORK_STATE" to "Allows applications to change network connectivity state.",
                "CHANGE_WIFI_MULTICAST_STATE" to "Allows applications to enter Wi-Fi Multicast mode.",
                "CHANGE_WIFI_STATE" to "Allows applications to change Wi-Fi connectivity state.",
                "CLEAR_APP_CACHE" to "Allows an application to clear the caches of all installed applications on the device.",
                "CONTROL_LOCATION_UPDATES" to "Allows enabling/disabling location update notifications from the radio.",
                "DELETE_CACHE_FILES" to "Allows an application to delete cache files.",
                "DELETE_PACKAGES" to "Allows an application to delete packages.",
                "DIAGNOSTIC" to "Allows applications to RW to diagnostic resources.",
                "DISABLE_KEYGUARD" to "Allows applications to disable the keyguard if it is not secure.",
                "DUMP" to "Allows an application to retrieve state dump information from system services.",
                "EXPAND_STATUS_BAR" to "Allows an application to expand or collapse the status bar.",
                "FACTORY_TEST" to "Run as a manufacturer test application, running as the root user.",
                "GET_ACCOUNTS" to "Allows access to the list of accounts in the Accounts Service.",
                "GET_ACCOUNTS_PRIVILEGED" to "Allows access to the list of accounts in the Accounts Service.",
                "GET_PACKAGE_SIZE" to "Allows an application to find out the space used by any package.",
                "GET_TASKS" to "This constant was deprecated in API level 21. No longer enforced.",
                "GLOBAL_SEARCH" to "This permission can be used on content providers to allow the global search system to access their data.",
                "INSTALL_LOCATION_PROVIDER" to "Allows an application to install a location provider into the Location Manager.",
                "INSTALL_PACKAGES" to "Allows an application to install packages.",
                "INSTALL_SHORTCUT" to "Allows an application to install a shortcut in Launcher.",
                "INSTANT_APP_FOREGROUND_SERVICE" to "Allows an instant app to create foreground services.",
                "INTERNET" to "Allows applications to open network sockets.",
                "KILL_BACKGROUND_PROCESSES" to "Allows an application to call killBackgroundProcesses",
                "LOCATION_HARDWARE" to "Allows an application to use location features in hardware, such as the geofencing api.",
                "MANAGE_DOCUMENTS" to "Allows an application to manage access to documents, usually as part of a document picker.",
                "MANAGE_OWN_CALLS" to "Allows an application to manage its own calls, but rely on the system to route focus to the currently active call.",
                "MASTER_CLEAR" to "Not for use by third-party applications.",
                "MEDIA_CONTENT_CONTROL" to "Allows an application to know what content is playing and control its playback.",
                "MODIFY_AUDIO_SETTINGS" to "Allows an application to modify global audio settings.",
                "MODIFY_PHONE_STATE" to "Allows modification of the telephony state - power on, mmi, etc.",
                "MOUNT_FORMAT_FILESYSTEMS" to "Allows formatting file systems for removable storage.",
                "MOUNT_UNMOUNT_FILESYSTEMS" to "Allows mounting and unmounting file systems for removable storage.",
                "NFC" to "Allows applications to perform I/O operations over NFC.",
                "PACKAGE_USAGE_STATS" to "Allows an application to collect component usage statistics. Declaring the permission implies intention to use the API and the user of the device can grant permission through the Settings application.",
                "PERSISTENT_ACTIVITY" to "This constant was deprecated in API level 9. This functionality will be removed in the future; please do not use. Allow an application to make its activities persistent.",
                "PROCESS_OUTGOING_CALLS" to "Allows an application to see the number being dialed during an outgoing call with the option to redirect the call to a different number or abort the call altogether.",
                "READ_CALENDAR" to "Allows an application to read the user's calendar data.",
                "READ_CALL_LOG" to "Allows an application to read the user's call log.",
                "READ_CONTACTS" to "Allows an application to read the user's contacts data.",
                "READ_EXTERNAL_STORAGE" to "Allows an application to read from external storage.",
                "READ_FRAME_BUFFER" to "Allows an application to take screen shots and more generally get access to the frame buffer data.",
                "READ_INPUT_STATE" to "This constant was deprecated in API level 16. The API that used this permission has been removed.",
                "READ_LOGS" to "Allows an application to read the low-level system log files.",
                "READ_PHONE_NUMBER" to "Allows read access to the device's phone number.",
                "READ_PHONE_STATE" to "Allows read only access to phone state, including the phone number of the device, current cellular network information, the status of any ongoing calls, and a list of any PhoneAccounts registered on the device.",
                "READ_SMS" to "Allows an application to read SMS messages.",
                "READ_SYNC_SETTINGS" to "Allows applications to read the sync settings.",
                "READ_SYNC_STATS" to "Allows applications to read the sync stats.",
                "READ_VOICEMAIL" to "Allows an application to read voicemails in the system.",
                "REBOOT" to "Required to be able to reboot the device.",
                "RECEIVE_BOOT_COMPLETED" to "Allows an application to receive the ACTION_BOOT_COMPLETED that is broadcast after the system finishes booting.",
                "RECEIVE_MMS" to "Allows an application to monitor incoming MMS messages.",
                "RECEIVE_SMS" to "Allows an application to receive SMS messages.",
                "RECEIVE_WAP_PUSH" to "Allows an application to receive WAP push messages.",
                "RECORD_AUDIO" to "Allows an application to record audio.",
                "REORDER_TASKS" to "Allows an application to change the Z-order of tasks.",
                "REQUEST_DELETE_PACKAGES" to "Allows an application to request deleting packages.",
                "REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" to "Permission an application must hold in order to use ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS.",
                "REQUEST_INSTALL_PACKAGES" to "Allows an application to request installing packages.",
                "RESTART_PACKAGES" to "This constant was deprecatd in API level 8. The restartPackage( API is no longer supported.",
                "RESTRICTED_VR_ACCESS" to "Must be required by system apps when accessing restricted VR APIs.",
                "RUN_IN_BACKGROUND" to "Allows an app to run in the background.",
                "SEND_RESPOND_VIA_MESSAGE" to "Allows an application (Phone) to send a request to other applications to handle the respond-via-message action during incoming calls.",
                "SEND_SMS" to "Allows an application to send SMS messages.",
                "SET_ALARM" to "Allows an application to broadcast an Intent to set an alarm for the user.",
                "SET_ALWAYS_FINISH" to "Allows an application to control whether activities are immediately finished when put in the background.",
                "SET_ANIMATION_SCALE" to "Modify the global animation scaling factor.",
                "SET_DEBUG_APP" to "Configure an application for debugging.",
                "SET_PREFERRED_APPLICATIONS" to "This constant was depreated in API level 7. No longer useful, see addPackageToPreferred( for details.",
                "SET_PROCESS_LIMIT" to "Allows an application to set the maximum number of (not needed) application processes that can be running.",
                "SET_TIME" to "Allows applications to set the system time.",
                "SET_TIME_ZONE" to "Allows applications to set the system time zone.",
                "SET_WALLPAPER" to "Allows applications to set the wallpaper.",
                "SET_WALLPAPER_HINTS" to "Allows applications to set the wallpaper hints.",
                "SIGNAL_PERSISTENT_PROCESSES" to "Allow an application to request that a signal be sent to all persistent processes.",
                "STATUS_BAR" to "Allows an application to open, close, or disable the status bar and its icons.",
                "SYSTEM_ALERT_WINDOW" to "Allows an app to create windows using the type TYPE_APPLICATION_OVERLAY, shown on top of all other apps.",
                "TRANSMIT_IR" to "Allows using the device's IR transmitter, if available.",
                "UNINSTALL_SHORTCUT" to "This permission is no longer supported.",
                "UPDATE_DEVICE_STATS" to "Allows an application to update device statistics.",
                "USE_DATA_IN_BACKGROUND" to "Allows an app to use data in the background.",
                "USE_FINGERPRINT" to "Allows an app to use fingerprint hardware.",
                "USE_SIP" to "Allows an application to use SIP service.",
                "VIBRATE" to "Allows access to the vibrator.",
                "WAKE_LOCK" to "Allows using PowerManager WakeLocks to keep processor from sleeping or screen from dimming.",
                "WRITE_APN_SETTINGS" to "Allows applications to write the apn settings.",
                "WRITE_CALENDAR" to "Allows an application to write the user's calendar data.",
                "WRITE_CALL_LOG" to "Allows an application to write (but not read) the user's call log data.",
                "WRITE_CONTACTS" to "Allows an application to write the user's contacts data.",
                "WRITE_EXTERNAL_STORAGE" to "Allows an application to write to external storage.",
                "WRITE_GSERVICES" to "Allows an application to modify the Google service map.",
                "WRITE_SECURE_SETTINGS" to "Allows an application to read or write the secure system settings.",
                "WRITE_SETTINGS" to "Allows an application to read or write the system settings.",
                "WRITE_SYNC_SETTINGS" to "Allows applications to write the sync settings.",
                "WRITE_VOICEMAIL" to "Allows an application to modify and remove existing voicemails in the system."
        )
    }
}