// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

public interface AndroidBuildProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AndroidBuildProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>optional string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string product = 2;</code>
   */
  boolean hasProduct();
  /**
   * <code>optional string product = 2;</code>
   */
  java.lang.String getProduct();
  /**
   * <code>optional string product = 2;</code>
   */
  com.google.protobuf.ByteString
      getProductBytes();

  /**
   * <code>optional string carrier = 3;</code>
   */
  boolean hasCarrier();
  /**
   * <code>optional string carrier = 3;</code>
   */
  java.lang.String getCarrier();
  /**
   * <code>optional string carrier = 3;</code>
   */
  com.google.protobuf.ByteString
      getCarrierBytes();

  /**
   * <code>optional string radio = 4;</code>
   */
  boolean hasRadio();
  /**
   * <code>optional string radio = 4;</code>
   */
  java.lang.String getRadio();
  /**
   * <code>optional string radio = 4;</code>
   */
  com.google.protobuf.ByteString
      getRadioBytes();

  /**
   * <code>optional string bootloader = 5;</code>
   */
  boolean hasBootloader();
  /**
   * <code>optional string bootloader = 5;</code>
   */
  java.lang.String getBootloader();
  /**
   * <code>optional string bootloader = 5;</code>
   */
  com.google.protobuf.ByteString
      getBootloaderBytes();

  /**
   * <code>optional string client = 6;</code>
   */
  boolean hasClient();
  /**
   * <code>optional string client = 6;</code>
   */
  java.lang.String getClient();
  /**
   * <code>optional string client = 6;</code>
   */
  com.google.protobuf.ByteString
      getClientBytes();

  /**
   * <code>optional int64 timestamp = 7;</code>
   */
  boolean hasTimestamp();
  /**
   * <code>optional int64 timestamp = 7;</code>
   */
  long getTimestamp();

  /**
   * <code>optional int32 googleServices = 8;</code>
   */
  boolean hasGoogleServices();
  /**
   * <code>optional int32 googleServices = 8;</code>
   */
  int getGoogleServices();

  /**
   * <code>optional string device = 9;</code>
   */
  boolean hasDevice();
  /**
   * <code>optional string device = 9;</code>
   */
  java.lang.String getDevice();
  /**
   * <code>optional string device = 9;</code>
   */
  com.google.protobuf.ByteString
      getDeviceBytes();

  /**
   * <code>optional int32 sdkVersion = 10;</code>
   */
  boolean hasSdkVersion();
  /**
   * <code>optional int32 sdkVersion = 10;</code>
   */
  int getSdkVersion();

  /**
   * <code>optional string model = 11;</code>
   */
  boolean hasModel();
  /**
   * <code>optional string model = 11;</code>
   */
  java.lang.String getModel();
  /**
   * <code>optional string model = 11;</code>
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>optional string manufacturer = 12;</code>
   */
  boolean hasManufacturer();
  /**
   * <code>optional string manufacturer = 12;</code>
   */
  java.lang.String getManufacturer();
  /**
   * <code>optional string manufacturer = 12;</code>
   */
  com.google.protobuf.ByteString
      getManufacturerBytes();

  /**
   * <code>optional string buildProduct = 13;</code>
   */
  boolean hasBuildProduct();
  /**
   * <code>optional string buildProduct = 13;</code>
   */
  java.lang.String getBuildProduct();
  /**
   * <code>optional string buildProduct = 13;</code>
   */
  com.google.protobuf.ByteString
      getBuildProductBytes();

  /**
   * <code>optional bool otaInstalled = 14;</code>
   */
  boolean hasOtaInstalled();
  /**
   * <code>optional bool otaInstalled = 14;</code>
   */
  boolean getOtaInstalled();
}
