// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

public interface BulkDetailsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BulkDetailsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .BulkDetailsEntry entry = 1;</code>
   */
  java.util.List<com.thunderclouddev.playstoreapi.proto.BulkDetailsEntry>
      getEntryList();
  /**
   * <code>repeated .BulkDetailsEntry entry = 1;</code>
   */
  com.thunderclouddev.playstoreapi.proto.BulkDetailsEntry getEntry(int index);
  /**
   * <code>repeated .BulkDetailsEntry entry = 1;</code>
   */
  int getEntryCount();
  /**
   * <code>repeated .BulkDetailsEntry entry = 1;</code>
   */
  java.util.List<? extends com.thunderclouddev.playstoreapi.proto.BulkDetailsEntryOrBuilder>
      getEntryOrBuilderList();
  /**
   * <code>repeated .BulkDetailsEntry entry = 1;</code>
   */
  com.thunderclouddev.playstoreapi.proto.BulkDetailsEntryOrBuilder getEntryOrBuilder(
      int index);
}
