// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

public interface EfeParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EfeParam)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 key = 1;</code>
   */
  boolean hasKey();
  /**
   * <code>optional int32 key = 1;</code>
   */
  int getKey();

  /**
   * <code>optional string value = 2;</code>
   */
  boolean hasValue();
  /**
   * <code>optional string value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <code>optional string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
