// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

public interface RelatedLinksOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RelatedLinks)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .RelatedLinksUnknown1 unknown1 = 10;</code>
   */
  boolean hasUnknown1();
  /**
   * <code>optional .RelatedLinksUnknown1 unknown1 = 10;</code>
   */
  com.thunderclouddev.playstoreapi.proto.RelatedLinksUnknown1 getUnknown1();
  /**
   * <code>optional .RelatedLinksUnknown1 unknown1 = 10;</code>
   */
  com.thunderclouddev.playstoreapi.proto.RelatedLinksUnknown1OrBuilder getUnknown1OrBuilder();

  /**
   * <code>optional string privacyPolicyUrl = 18;</code>
   */
  boolean hasPrivacyPolicyUrl();
  /**
   * <code>optional string privacyPolicyUrl = 18;</code>
   */
  java.lang.String getPrivacyPolicyUrl();
  /**
   * <code>optional string privacyPolicyUrl = 18;</code>
   */
  com.google.protobuf.ByteString
      getPrivacyPolicyUrlBytes();

  /**
   * <code>optional .RelatedLink youMightAlsoLike = 24;</code>
   */
  boolean hasYouMightAlsoLike();
  /**
   * <code>optional .RelatedLink youMightAlsoLike = 24;</code>
   */
  com.thunderclouddev.playstoreapi.proto.RelatedLink getYouMightAlsoLike();
  /**
   * <code>optional .RelatedLink youMightAlsoLike = 24;</code>
   */
  com.thunderclouddev.playstoreapi.proto.RelatedLinkOrBuilder getYouMightAlsoLikeOrBuilder();

  /**
   * <code>optional .Rated rated = 29;</code>
   */
  boolean hasRated();
  /**
   * <code>optional .Rated rated = 29;</code>
   */
  com.thunderclouddev.playstoreapi.proto.Rated getRated();
  /**
   * <code>optional .Rated rated = 29;</code>
   */
  com.thunderclouddev.playstoreapi.proto.RatedOrBuilder getRatedOrBuilder();

  /**
   * <code>repeated .RelatedLink relatedLinks = 34;</code>
   */
  java.util.List<com.thunderclouddev.playstoreapi.proto.RelatedLink>
      getRelatedLinksList();
  /**
   * <code>repeated .RelatedLink relatedLinks = 34;</code>
   */
  com.thunderclouddev.playstoreapi.proto.RelatedLink getRelatedLinks(int index);
  /**
   * <code>repeated .RelatedLink relatedLinks = 34;</code>
   */
  int getRelatedLinksCount();
  /**
   * <code>repeated .RelatedLink relatedLinks = 34;</code>
   */
  java.util.List<? extends com.thunderclouddev.playstoreapi.proto.RelatedLinkOrBuilder>
      getRelatedLinksOrBuilderList();
  /**
   * <code>repeated .RelatedLink relatedLinks = 34;</code>
   */
  com.thunderclouddev.playstoreapi.proto.RelatedLinkOrBuilder getRelatedLinksOrBuilder(
      int index);

  /**
   * <code>optional .CategoryInfo categoryInfo = 53;</code>
   */
  boolean hasCategoryInfo();
  /**
   * <code>optional .CategoryInfo categoryInfo = 53;</code>
   */
  com.thunderclouddev.playstoreapi.proto.CategoryInfo getCategoryInfo();
  /**
   * <code>optional .CategoryInfo categoryInfo = 53;</code>
   */
  com.thunderclouddev.playstoreapi.proto.CategoryInfoOrBuilder getCategoryInfoOrBuilder();
}
