// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

/**
 * Protobuf type {@code Rule}
 */
public final class Rule extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Rule)
    RuleOrBuilder {
  // Use Rule.newBuilder() to construct.
  private Rule(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private Rule(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final Rule defaultInstance;
  public static Rule getDefaultInstance() {
    return defaultInstance;
  }

  public Rule getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private Rule(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            negate_ = input.readBool();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            operator_ = input.readInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            key_ = input.readInt32();
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              stringArg_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000008;
            }
            stringArg_.add(bs);
            break;
          }
          case 40: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              longArg_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000010;
            }
            longArg_.add(input.readInt64());
            break;
          }
          case 42: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
              longArg_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000010;
            }
            while (input.getBytesUntilLimit() > 0) {
              longArg_.add(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 49: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              doubleArg_ = new java.util.ArrayList<java.lang.Double>();
              mutable_bitField0_ |= 0x00000020;
            }
            doubleArg_.add(input.readDouble());
            break;
          }
          case 50: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020) && input.getBytesUntilLimit() > 0) {
              doubleArg_ = new java.util.ArrayList<java.lang.Double>();
              mutable_bitField0_ |= 0x00000020;
            }
            while (input.getBytesUntilLimit() > 0) {
              doubleArg_.add(input.readDouble());
            }
            input.popLimit(limit);
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              subrule_ = new java.util.ArrayList<com.thunderclouddev.playstoreapi.proto.Rule>();
              mutable_bitField0_ |= 0x00000040;
            }
            subrule_.add(input.readMessage(com.thunderclouddev.playstoreapi.proto.Rule.PARSER, extensionRegistry));
            break;
          }
          case 64: {
            bitField0_ |= 0x00000008;
            responseCode_ = input.readInt32();
            break;
          }
          case 74: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            comment_ = bs;
            break;
          }
          case 81: {
            if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
              stringArgHash_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000200;
            }
            stringArgHash_.add(input.readFixed64());
            break;
          }
          case 82: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000200) == 0x00000200) && input.getBytesUntilLimit() > 0) {
              stringArgHash_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000200;
            }
            while (input.getBytesUntilLimit() > 0) {
              stringArgHash_.add(input.readFixed64());
            }
            input.popLimit(limit);
            break;
          }
          case 88: {
            if (!((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
              constArg_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000400;
            }
            constArg_.add(input.readInt32());
            break;
          }
          case 90: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000400) == 0x00000400) && input.getBytesUntilLimit() > 0) {
              constArg_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000400;
            }
            while (input.getBytesUntilLimit() > 0) {
              constArg_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        stringArg_ = stringArg_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        longArg_ = java.util.Collections.unmodifiableList(longArg_);
      }
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        doubleArg_ = java.util.Collections.unmodifiableList(doubleArg_);
      }
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        subrule_ = java.util.Collections.unmodifiableList(subrule_);
      }
      if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
        stringArgHash_ = java.util.Collections.unmodifiableList(stringArgHash_);
      }
      if (((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
        constArg_ = java.util.Collections.unmodifiableList(constArg_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.thunderclouddev.playstoreapi.proto.GooglePlay.internal_static_Rule_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.thunderclouddev.playstoreapi.proto.GooglePlay.internal_static_Rule_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.thunderclouddev.playstoreapi.proto.Rule.class, com.thunderclouddev.playstoreapi.proto.Rule.Builder.class);
  }

  public static com.google.protobuf.Parser<Rule> PARSER =
      new com.google.protobuf.AbstractParser<Rule>() {
    public Rule parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Rule(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<Rule> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int NEGATE_FIELD_NUMBER = 1;
  private boolean negate_;
  /**
   * <code>optional bool negate = 1;</code>
   */
  public boolean hasNegate() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional bool negate = 1;</code>
   */
  public boolean getNegate() {
    return negate_;
  }

  public static final int OPERATOR_FIELD_NUMBER = 2;
  private int operator_;
  /**
   * <code>optional int32 operator = 2;</code>
   */
  public boolean hasOperator() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional int32 operator = 2;</code>
   */
  public int getOperator() {
    return operator_;
  }

  public static final int KEY_FIELD_NUMBER = 3;
  private int key_;
  /**
   * <code>optional int32 key = 3;</code>
   */
  public boolean hasKey() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional int32 key = 3;</code>
   */
  public int getKey() {
    return key_;
  }

  public static final int STRINGARG_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList stringArg_;
  /**
   * <code>repeated string stringArg = 4;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getStringArgList() {
    return stringArg_;
  }
  /**
   * <code>repeated string stringArg = 4;</code>
   */
  public int getStringArgCount() {
    return stringArg_.size();
  }
  /**
   * <code>repeated string stringArg = 4;</code>
   */
  public java.lang.String getStringArg(int index) {
    return stringArg_.get(index);
  }
  /**
   * <code>repeated string stringArg = 4;</code>
   */
  public com.google.protobuf.ByteString
      getStringArgBytes(int index) {
    return stringArg_.getByteString(index);
  }

  public static final int LONGARG_FIELD_NUMBER = 5;
  private java.util.List<java.lang.Long> longArg_;
  /**
   * <code>repeated int64 longArg = 5;</code>
   */
  public java.util.List<java.lang.Long>
      getLongArgList() {
    return longArg_;
  }
  /**
   * <code>repeated int64 longArg = 5;</code>
   */
  public int getLongArgCount() {
    return longArg_.size();
  }
  /**
   * <code>repeated int64 longArg = 5;</code>
   */
  public long getLongArg(int index) {
    return longArg_.get(index);
  }

  public static final int DOUBLEARG_FIELD_NUMBER = 6;
  private java.util.List<java.lang.Double> doubleArg_;
  /**
   * <code>repeated double doubleArg = 6;</code>
   */
  public java.util.List<java.lang.Double>
      getDoubleArgList() {
    return doubleArg_;
  }
  /**
   * <code>repeated double doubleArg = 6;</code>
   */
  public int getDoubleArgCount() {
    return doubleArg_.size();
  }
  /**
   * <code>repeated double doubleArg = 6;</code>
   */
  public double getDoubleArg(int index) {
    return doubleArg_.get(index);
  }

  public static final int SUBRULE_FIELD_NUMBER = 7;
  private java.util.List<com.thunderclouddev.playstoreapi.proto.Rule> subrule_;
  /**
   * <code>repeated .Rule subrule = 7;</code>
   */
  public java.util.List<com.thunderclouddev.playstoreapi.proto.Rule> getSubruleList() {
    return subrule_;
  }
  /**
   * <code>repeated .Rule subrule = 7;</code>
   */
  public java.util.List<? extends com.thunderclouddev.playstoreapi.proto.RuleOrBuilder>
      getSubruleOrBuilderList() {
    return subrule_;
  }
  /**
   * <code>repeated .Rule subrule = 7;</code>
   */
  public int getSubruleCount() {
    return subrule_.size();
  }
  /**
   * <code>repeated .Rule subrule = 7;</code>
   */
  public com.thunderclouddev.playstoreapi.proto.Rule getSubrule(int index) {
    return subrule_.get(index);
  }
  /**
   * <code>repeated .Rule subrule = 7;</code>
   */
  public com.thunderclouddev.playstoreapi.proto.RuleOrBuilder getSubruleOrBuilder(
      int index) {
    return subrule_.get(index);
  }

  public static final int RESPONSECODE_FIELD_NUMBER = 8;
  private int responseCode_;
  /**
   * <code>optional int32 responseCode = 8;</code>
   */
  public boolean hasResponseCode() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional int32 responseCode = 8;</code>
   */
  public int getResponseCode() {
    return responseCode_;
  }

  public static final int COMMENT_FIELD_NUMBER = 9;
  private java.lang.Object comment_;
  /**
   * <code>optional string comment = 9;</code>
   */
  public boolean hasComment() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional string comment = 9;</code>
   */
  public java.lang.String getComment() {
    java.lang.Object ref = comment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        comment_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string comment = 9;</code>
   */
  public com.google.protobuf.ByteString
      getCommentBytes() {
    java.lang.Object ref = comment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      comment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STRINGARGHASH_FIELD_NUMBER = 10;
  private java.util.List<java.lang.Long> stringArgHash_;
  /**
   * <code>repeated fixed64 stringArgHash = 10;</code>
   */
  public java.util.List<java.lang.Long>
      getStringArgHashList() {
    return stringArgHash_;
  }
  /**
   * <code>repeated fixed64 stringArgHash = 10;</code>
   */
  public int getStringArgHashCount() {
    return stringArgHash_.size();
  }
  /**
   * <code>repeated fixed64 stringArgHash = 10;</code>
   */
  public long getStringArgHash(int index) {
    return stringArgHash_.get(index);
  }

  public static final int CONSTARG_FIELD_NUMBER = 11;
  private java.util.List<java.lang.Integer> constArg_;
  /**
   * <code>repeated int32 constArg = 11;</code>
   */
  public java.util.List<java.lang.Integer>
      getConstArgList() {
    return constArg_;
  }
  /**
   * <code>repeated int32 constArg = 11;</code>
   */
  public int getConstArgCount() {
    return constArg_.size();
  }
  /**
   * <code>repeated int32 constArg = 11;</code>
   */
  public int getConstArg(int index) {
    return constArg_.get(index);
  }

  private void initFields() {
    negate_ = false;
    operator_ = 0;
    key_ = 0;
    stringArg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    longArg_ = java.util.Collections.emptyList();
    doubleArg_ = java.util.Collections.emptyList();
    subrule_ = java.util.Collections.emptyList();
    responseCode_ = 0;
    comment_ = "";
    stringArgHash_ = java.util.Collections.emptyList();
    constArg_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBool(1, negate_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, operator_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(3, key_);
    }
    for (int i = 0; i < stringArg_.size(); i++) {
      output.writeBytes(4, stringArg_.getByteString(i));
    }
    for (int i = 0; i < longArg_.size(); i++) {
      output.writeInt64(5, longArg_.get(i));
    }
    for (int i = 0; i < doubleArg_.size(); i++) {
      output.writeDouble(6, doubleArg_.get(i));
    }
    for (int i = 0; i < subrule_.size(); i++) {
      output.writeMessage(7, subrule_.get(i));
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt32(8, responseCode_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeBytes(9, getCommentBytes());
    }
    for (int i = 0; i < stringArgHash_.size(); i++) {
      output.writeFixed64(10, stringArgHash_.get(i));
    }
    for (int i = 0; i < constArg_.size(); i++) {
      output.writeInt32(11, constArg_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, negate_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, operator_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, key_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < stringArg_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(stringArg_.getByteString(i));
      }
      size += dataSize;
      size += 1 * getStringArgList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < longArg_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(longArg_.get(i));
      }
      size += dataSize;
      size += 1 * getLongArgList().size();
    }
    {
      int dataSize = 0;
      dataSize = 8 * getDoubleArgList().size();
      size += dataSize;
      size += 1 * getDoubleArgList().size();
    }
    for (int i = 0; i < subrule_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, subrule_.get(i));
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, responseCode_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(9, getCommentBytes());
    }
    {
      int dataSize = 0;
      dataSize = 8 * getStringArgHashList().size();
      size += dataSize;
      size += 1 * getStringArgHashList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < constArg_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(constArg_.get(i));
      }
      size += dataSize;
      size += 1 * getConstArgList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.thunderclouddev.playstoreapi.proto.Rule parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thunderclouddev.playstoreapi.proto.Rule parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thunderclouddev.playstoreapi.proto.Rule parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thunderclouddev.playstoreapi.proto.Rule parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thunderclouddev.playstoreapi.proto.Rule parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.thunderclouddev.playstoreapi.proto.Rule parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.thunderclouddev.playstoreapi.proto.Rule parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.thunderclouddev.playstoreapi.proto.Rule parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.thunderclouddev.playstoreapi.proto.Rule parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.thunderclouddev.playstoreapi.proto.Rule parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.thunderclouddev.playstoreapi.proto.Rule prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Rule}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Rule)
      com.thunderclouddev.playstoreapi.proto.RuleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thunderclouddev.playstoreapi.proto.GooglePlay.internal_static_Rule_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thunderclouddev.playstoreapi.proto.GooglePlay.internal_static_Rule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thunderclouddev.playstoreapi.proto.Rule.class, com.thunderclouddev.playstoreapi.proto.Rule.Builder.class);
    }

    // Construct using com.thunderclouddev.playstoreapi.proto.Rule.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getSubruleFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      negate_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      operator_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      key_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      stringArg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      longArg_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);
      doubleArg_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);
      if (subruleBuilder_ == null) {
        subrule_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
      } else {
        subruleBuilder_.clear();
      }
      responseCode_ = 0;
      bitField0_ = (bitField0_ & ~0x00000080);
      comment_ = "";
      bitField0_ = (bitField0_ & ~0x00000100);
      stringArgHash_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000200);
      constArg_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000400);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.thunderclouddev.playstoreapi.proto.GooglePlay.internal_static_Rule_descriptor;
    }

    public com.thunderclouddev.playstoreapi.proto.Rule getDefaultInstanceForType() {
      return com.thunderclouddev.playstoreapi.proto.Rule.getDefaultInstance();
    }

    public com.thunderclouddev.playstoreapi.proto.Rule build() {
      com.thunderclouddev.playstoreapi.proto.Rule result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.thunderclouddev.playstoreapi.proto.Rule buildPartial() {
      com.thunderclouddev.playstoreapi.proto.Rule result = new com.thunderclouddev.playstoreapi.proto.Rule(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.negate_ = negate_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.operator_ = operator_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.key_ = key_;
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        stringArg_ = stringArg_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.stringArg_ = stringArg_;
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        longArg_ = java.util.Collections.unmodifiableList(longArg_);
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.longArg_ = longArg_;
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        doubleArg_ = java.util.Collections.unmodifiableList(doubleArg_);
        bitField0_ = (bitField0_ & ~0x00000020);
      }
      result.doubleArg_ = doubleArg_;
      if (subruleBuilder_ == null) {
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          subrule_ = java.util.Collections.unmodifiableList(subrule_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.subrule_ = subrule_;
      } else {
        result.subrule_ = subruleBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000008;
      }
      result.responseCode_ = responseCode_;
      if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
        to_bitField0_ |= 0x00000010;
      }
      result.comment_ = comment_;
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        stringArgHash_ = java.util.Collections.unmodifiableList(stringArgHash_);
        bitField0_ = (bitField0_ & ~0x00000200);
      }
      result.stringArgHash_ = stringArgHash_;
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        constArg_ = java.util.Collections.unmodifiableList(constArg_);
        bitField0_ = (bitField0_ & ~0x00000400);
      }
      result.constArg_ = constArg_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.thunderclouddev.playstoreapi.proto.Rule) {
        return mergeFrom((com.thunderclouddev.playstoreapi.proto.Rule)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.thunderclouddev.playstoreapi.proto.Rule other) {
      if (other == com.thunderclouddev.playstoreapi.proto.Rule.getDefaultInstance()) return this;
      if (other.hasNegate()) {
        setNegate(other.getNegate());
      }
      if (other.hasOperator()) {
        setOperator(other.getOperator());
      }
      if (other.hasKey()) {
        setKey(other.getKey());
      }
      if (!other.stringArg_.isEmpty()) {
        if (stringArg_.isEmpty()) {
          stringArg_ = other.stringArg_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureStringArgIsMutable();
          stringArg_.addAll(other.stringArg_);
        }
        onChanged();
      }
      if (!other.longArg_.isEmpty()) {
        if (longArg_.isEmpty()) {
          longArg_ = other.longArg_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureLongArgIsMutable();
          longArg_.addAll(other.longArg_);
        }
        onChanged();
      }
      if (!other.doubleArg_.isEmpty()) {
        if (doubleArg_.isEmpty()) {
          doubleArg_ = other.doubleArg_;
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          ensureDoubleArgIsMutable();
          doubleArg_.addAll(other.doubleArg_);
        }
        onChanged();
      }
      if (subruleBuilder_ == null) {
        if (!other.subrule_.isEmpty()) {
          if (subrule_.isEmpty()) {
            subrule_ = other.subrule_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureSubruleIsMutable();
            subrule_.addAll(other.subrule_);
          }
          onChanged();
        }
      } else {
        if (!other.subrule_.isEmpty()) {
          if (subruleBuilder_.isEmpty()) {
            subruleBuilder_.dispose();
            subruleBuilder_ = null;
            subrule_ = other.subrule_;
            bitField0_ = (bitField0_ & ~0x00000040);
            subruleBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getSubruleFieldBuilder() : null;
          } else {
            subruleBuilder_.addAllMessages(other.subrule_);
          }
        }
      }
      if (other.hasResponseCode()) {
        setResponseCode(other.getResponseCode());
      }
      if (other.hasComment()) {
        bitField0_ |= 0x00000100;
        comment_ = other.comment_;
        onChanged();
      }
      if (!other.stringArgHash_.isEmpty()) {
        if (stringArgHash_.isEmpty()) {
          stringArgHash_ = other.stringArgHash_;
          bitField0_ = (bitField0_ & ~0x00000200);
        } else {
          ensureStringArgHashIsMutable();
          stringArgHash_.addAll(other.stringArgHash_);
        }
        onChanged();
      }
      if (!other.constArg_.isEmpty()) {
        if (constArg_.isEmpty()) {
          constArg_ = other.constArg_;
          bitField0_ = (bitField0_ & ~0x00000400);
        } else {
          ensureConstArgIsMutable();
          constArg_.addAll(other.constArg_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.thunderclouddev.playstoreapi.proto.Rule parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.thunderclouddev.playstoreapi.proto.Rule) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean negate_ ;
    /**
     * <code>optional bool negate = 1;</code>
     */
    public boolean hasNegate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool negate = 1;</code>
     */
    public boolean getNegate() {
      return negate_;
    }
    /**
     * <code>optional bool negate = 1;</code>
     */
    public Builder setNegate(boolean value) {
      bitField0_ |= 0x00000001;
      negate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool negate = 1;</code>
     */
    public Builder clearNegate() {
      bitField0_ = (bitField0_ & ~0x00000001);
      negate_ = false;
      onChanged();
      return this;
    }

    private int operator_ ;
    /**
     * <code>optional int32 operator = 2;</code>
     */
    public boolean hasOperator() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 operator = 2;</code>
     */
    public int getOperator() {
      return operator_;
    }
    /**
     * <code>optional int32 operator = 2;</code>
     */
    public Builder setOperator(int value) {
      bitField0_ |= 0x00000002;
      operator_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 operator = 2;</code>
     */
    public Builder clearOperator() {
      bitField0_ = (bitField0_ & ~0x00000002);
      operator_ = 0;
      onChanged();
      return this;
    }

    private int key_ ;
    /**
     * <code>optional int32 key = 3;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 key = 3;</code>
     */
    public int getKey() {
      return key_;
    }
    /**
     * <code>optional int32 key = 3;</code>
     */
    public Builder setKey(int value) {
      bitField0_ |= 0x00000004;
      key_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 key = 3;</code>
     */
    public Builder clearKey() {
      bitField0_ = (bitField0_ & ~0x00000004);
      key_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList stringArg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureStringArgIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        stringArg_ = new com.google.protobuf.LazyStringArrayList(stringArg_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated string stringArg = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getStringArgList() {
      return stringArg_.getUnmodifiableView();
    }
    /**
     * <code>repeated string stringArg = 4;</code>
     */
    public int getStringArgCount() {
      return stringArg_.size();
    }
    /**
     * <code>repeated string stringArg = 4;</code>
     */
    public java.lang.String getStringArg(int index) {
      return stringArg_.get(index);
    }
    /**
     * <code>repeated string stringArg = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStringArgBytes(int index) {
      return stringArg_.getByteString(index);
    }
    /**
     * <code>repeated string stringArg = 4;</code>
     */
    public Builder setStringArg(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureStringArgIsMutable();
      stringArg_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string stringArg = 4;</code>
     */
    public Builder addStringArg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureStringArgIsMutable();
      stringArg_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string stringArg = 4;</code>
     */
    public Builder addAllStringArg(
        java.lang.Iterable<java.lang.String> values) {
      ensureStringArgIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, stringArg_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string stringArg = 4;</code>
     */
    public Builder clearStringArg() {
      stringArg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string stringArg = 4;</code>
     */
    public Builder addStringArgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureStringArgIsMutable();
      stringArg_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Long> longArg_ = java.util.Collections.emptyList();
    private void ensureLongArgIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        longArg_ = new java.util.ArrayList<java.lang.Long>(longArg_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <code>repeated int64 longArg = 5;</code>
     */
    public java.util.List<java.lang.Long>
        getLongArgList() {
      return java.util.Collections.unmodifiableList(longArg_);
    }
    /**
     * <code>repeated int64 longArg = 5;</code>
     */
    public int getLongArgCount() {
      return longArg_.size();
    }
    /**
     * <code>repeated int64 longArg = 5;</code>
     */
    public long getLongArg(int index) {
      return longArg_.get(index);
    }
    /**
     * <code>repeated int64 longArg = 5;</code>
     */
    public Builder setLongArg(
        int index, long value) {
      ensureLongArgIsMutable();
      longArg_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 longArg = 5;</code>
     */
    public Builder addLongArg(long value) {
      ensureLongArgIsMutable();
      longArg_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 longArg = 5;</code>
     */
    public Builder addAllLongArg(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureLongArgIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, longArg_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 longArg = 5;</code>
     */
    public Builder clearLongArg() {
      longArg_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Double> doubleArg_ = java.util.Collections.emptyList();
    private void ensureDoubleArgIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        doubleArg_ = new java.util.ArrayList<java.lang.Double>(doubleArg_);
        bitField0_ |= 0x00000020;
       }
    }
    /**
     * <code>repeated double doubleArg = 6;</code>
     */
    public java.util.List<java.lang.Double>
        getDoubleArgList() {
      return java.util.Collections.unmodifiableList(doubleArg_);
    }
    /**
     * <code>repeated double doubleArg = 6;</code>
     */
    public int getDoubleArgCount() {
      return doubleArg_.size();
    }
    /**
     * <code>repeated double doubleArg = 6;</code>
     */
    public double getDoubleArg(int index) {
      return doubleArg_.get(index);
    }
    /**
     * <code>repeated double doubleArg = 6;</code>
     */
    public Builder setDoubleArg(
        int index, double value) {
      ensureDoubleArgIsMutable();
      doubleArg_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double doubleArg = 6;</code>
     */
    public Builder addDoubleArg(double value) {
      ensureDoubleArgIsMutable();
      doubleArg_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double doubleArg = 6;</code>
     */
    public Builder addAllDoubleArg(
        java.lang.Iterable<? extends java.lang.Double> values) {
      ensureDoubleArgIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, doubleArg_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double doubleArg = 6;</code>
     */
    public Builder clearDoubleArg() {
      doubleArg_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }

    private java.util.List<com.thunderclouddev.playstoreapi.proto.Rule> subrule_ =
      java.util.Collections.emptyList();
    private void ensureSubruleIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        subrule_ = new java.util.ArrayList<com.thunderclouddev.playstoreapi.proto.Rule>(subrule_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.thunderclouddev.playstoreapi.proto.Rule, com.thunderclouddev.playstoreapi.proto.Rule.Builder, com.thunderclouddev.playstoreapi.proto.RuleOrBuilder> subruleBuilder_;

    /**
     * <code>repeated .Rule subrule = 7;</code>
     */
    public java.util.List<com.thunderclouddev.playstoreapi.proto.Rule> getSubruleList() {
      if (subruleBuilder_ == null) {
        return java.util.Collections.unmodifiableList(subrule_);
      } else {
        return subruleBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Rule subrule = 7;</code>
     */
    public int getSubruleCount() {
      if (subruleBuilder_ == null) {
        return subrule_.size();
      } else {
        return subruleBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Rule subrule = 7;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.Rule getSubrule(int index) {
      if (subruleBuilder_ == null) {
        return subrule_.get(index);
      } else {
        return subruleBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Rule subrule = 7;</code>
     */
    public Builder setSubrule(
        int index, com.thunderclouddev.playstoreapi.proto.Rule value) {
      if (subruleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubruleIsMutable();
        subrule_.set(index, value);
        onChanged();
      } else {
        subruleBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Rule subrule = 7;</code>
     */
    public Builder setSubrule(
        int index, com.thunderclouddev.playstoreapi.proto.Rule.Builder builderForValue) {
      if (subruleBuilder_ == null) {
        ensureSubruleIsMutable();
        subrule_.set(index, builderForValue.build());
        onChanged();
      } else {
        subruleBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Rule subrule = 7;</code>
     */
    public Builder addSubrule(com.thunderclouddev.playstoreapi.proto.Rule value) {
      if (subruleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubruleIsMutable();
        subrule_.add(value);
        onChanged();
      } else {
        subruleBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Rule subrule = 7;</code>
     */
    public Builder addSubrule(
        int index, com.thunderclouddev.playstoreapi.proto.Rule value) {
      if (subruleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubruleIsMutable();
        subrule_.add(index, value);
        onChanged();
      } else {
        subruleBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Rule subrule = 7;</code>
     */
    public Builder addSubrule(
        com.thunderclouddev.playstoreapi.proto.Rule.Builder builderForValue) {
      if (subruleBuilder_ == null) {
        ensureSubruleIsMutable();
        subrule_.add(builderForValue.build());
        onChanged();
      } else {
        subruleBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Rule subrule = 7;</code>
     */
    public Builder addSubrule(
        int index, com.thunderclouddev.playstoreapi.proto.Rule.Builder builderForValue) {
      if (subruleBuilder_ == null) {
        ensureSubruleIsMutable();
        subrule_.add(index, builderForValue.build());
        onChanged();
      } else {
        subruleBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Rule subrule = 7;</code>
     */
    public Builder addAllSubrule(
        java.lang.Iterable<? extends com.thunderclouddev.playstoreapi.proto.Rule> values) {
      if (subruleBuilder_ == null) {
        ensureSubruleIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, subrule_);
        onChanged();
      } else {
        subruleBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Rule subrule = 7;</code>
     */
    public Builder clearSubrule() {
      if (subruleBuilder_ == null) {
        subrule_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        subruleBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Rule subrule = 7;</code>
     */
    public Builder removeSubrule(int index) {
      if (subruleBuilder_ == null) {
        ensureSubruleIsMutable();
        subrule_.remove(index);
        onChanged();
      } else {
        subruleBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Rule subrule = 7;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.Rule.Builder getSubruleBuilder(
        int index) {
      return getSubruleFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Rule subrule = 7;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.RuleOrBuilder getSubruleOrBuilder(
        int index) {
      if (subruleBuilder_ == null) {
        return subrule_.get(index);  } else {
        return subruleBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Rule subrule = 7;</code>
     */
    public java.util.List<? extends com.thunderclouddev.playstoreapi.proto.RuleOrBuilder>
         getSubruleOrBuilderList() {
      if (subruleBuilder_ != null) {
        return subruleBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(subrule_);
      }
    }
    /**
     * <code>repeated .Rule subrule = 7;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.Rule.Builder addSubruleBuilder() {
      return getSubruleFieldBuilder().addBuilder(
          com.thunderclouddev.playstoreapi.proto.Rule.getDefaultInstance());
    }
    /**
     * <code>repeated .Rule subrule = 7;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.Rule.Builder addSubruleBuilder(
        int index) {
      return getSubruleFieldBuilder().addBuilder(
          index, com.thunderclouddev.playstoreapi.proto.Rule.getDefaultInstance());
    }
    /**
     * <code>repeated .Rule subrule = 7;</code>
     */
    public java.util.List<com.thunderclouddev.playstoreapi.proto.Rule.Builder>
         getSubruleBuilderList() {
      return getSubruleFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.thunderclouddev.playstoreapi.proto.Rule, com.thunderclouddev.playstoreapi.proto.Rule.Builder, com.thunderclouddev.playstoreapi.proto.RuleOrBuilder>
        getSubruleFieldBuilder() {
      if (subruleBuilder_ == null) {
        subruleBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.thunderclouddev.playstoreapi.proto.Rule, com.thunderclouddev.playstoreapi.proto.Rule.Builder, com.thunderclouddev.playstoreapi.proto.RuleOrBuilder>(
                subrule_,
                ((bitField0_ & 0x00000040) == 0x00000040),
                getParentForChildren(),
                isClean());
        subrule_ = null;
      }
      return subruleBuilder_;
    }

    private int responseCode_ ;
    /**
     * <code>optional int32 responseCode = 8;</code>
     */
    public boolean hasResponseCode() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 responseCode = 8;</code>
     */
    public int getResponseCode() {
      return responseCode_;
    }
    /**
     * <code>optional int32 responseCode = 8;</code>
     */
    public Builder setResponseCode(int value) {
      bitField0_ |= 0x00000080;
      responseCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 responseCode = 8;</code>
     */
    public Builder clearResponseCode() {
      bitField0_ = (bitField0_ & ~0x00000080);
      responseCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object comment_ = "";
    /**
     * <code>optional string comment = 9;</code>
     */
    public boolean hasComment() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string comment = 9;</code>
     */
    public java.lang.String getComment() {
      java.lang.Object ref = comment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          comment_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string comment = 9;</code>
     */
    public com.google.protobuf.ByteString
        getCommentBytes() {
      java.lang.Object ref = comment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string comment = 9;</code>
     */
    public Builder setComment(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      comment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string comment = 9;</code>
     */
    public Builder clearComment() {
      bitField0_ = (bitField0_ & ~0x00000100);
      comment_ = getDefaultInstance().getComment();
      onChanged();
      return this;
    }
    /**
     * <code>optional string comment = 9;</code>
     */
    public Builder setCommentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      comment_ = value;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Long> stringArgHash_ = java.util.Collections.emptyList();
    private void ensureStringArgHashIsMutable() {
      if (!((bitField0_ & 0x00000200) == 0x00000200)) {
        stringArgHash_ = new java.util.ArrayList<java.lang.Long>(stringArgHash_);
        bitField0_ |= 0x00000200;
       }
    }
    /**
     * <code>repeated fixed64 stringArgHash = 10;</code>
     */
    public java.util.List<java.lang.Long>
        getStringArgHashList() {
      return java.util.Collections.unmodifiableList(stringArgHash_);
    }
    /**
     * <code>repeated fixed64 stringArgHash = 10;</code>
     */
    public int getStringArgHashCount() {
      return stringArgHash_.size();
    }
    /**
     * <code>repeated fixed64 stringArgHash = 10;</code>
     */
    public long getStringArgHash(int index) {
      return stringArgHash_.get(index);
    }
    /**
     * <code>repeated fixed64 stringArgHash = 10;</code>
     */
    public Builder setStringArgHash(
        int index, long value) {
      ensureStringArgHashIsMutable();
      stringArgHash_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated fixed64 stringArgHash = 10;</code>
     */
    public Builder addStringArgHash(long value) {
      ensureStringArgHashIsMutable();
      stringArgHash_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated fixed64 stringArgHash = 10;</code>
     */
    public Builder addAllStringArgHash(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureStringArgHashIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, stringArgHash_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated fixed64 stringArgHash = 10;</code>
     */
    public Builder clearStringArgHash() {
      stringArgHash_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> constArg_ = java.util.Collections.emptyList();
    private void ensureConstArgIsMutable() {
      if (!((bitField0_ & 0x00000400) == 0x00000400)) {
        constArg_ = new java.util.ArrayList<java.lang.Integer>(constArg_);
        bitField0_ |= 0x00000400;
       }
    }
    /**
     * <code>repeated int32 constArg = 11;</code>
     */
    public java.util.List<java.lang.Integer>
        getConstArgList() {
      return java.util.Collections.unmodifiableList(constArg_);
    }
    /**
     * <code>repeated int32 constArg = 11;</code>
     */
    public int getConstArgCount() {
      return constArg_.size();
    }
    /**
     * <code>repeated int32 constArg = 11;</code>
     */
    public int getConstArg(int index) {
      return constArg_.get(index);
    }
    /**
     * <code>repeated int32 constArg = 11;</code>
     */
    public Builder setConstArg(
        int index, int value) {
      ensureConstArgIsMutable();
      constArg_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 constArg = 11;</code>
     */
    public Builder addConstArg(int value) {
      ensureConstArgIsMutable();
      constArg_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 constArg = 11;</code>
     */
    public Builder addAllConstArg(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureConstArgIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, constArg_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 constArg = 11;</code>
     */
    public Builder clearConstArg() {
      constArg_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Rule)
  }

  static {
    defaultInstance = new Rule(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:Rule)
}

