// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

public interface Unknown25ItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Unknown25Item)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string label = 1;</code>
   */
  boolean hasLabel();
  /**
   * <code>optional string label = 1;</code>
   */
  java.lang.String getLabel();
  /**
   * <code>optional string label = 1;</code>
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>optional .Unknown25Container container = 3;</code>
   */
  boolean hasContainer();
  /**
   * <code>optional .Unknown25Container container = 3;</code>
   */
  com.thunderclouddev.playstoreapi.proto.Unknown25Container getContainer();
  /**
   * <code>optional .Unknown25Container container = 3;</code>
   */
  com.thunderclouddev.playstoreapi.proto.Unknown25ContainerOrBuilder getContainerOrBuilder();
}
