/*
 * Copyright (c) 2017.
 * Distributed under the GNU GPLv3 by David Whitman.
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This source code is made available to help others learn. Please don't clone my app.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

public interface AlbumDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AlbumDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   */
  String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional .MusicDetails details = 2;</code>
   */
  boolean hasDetails();
  /**
   * <code>optional .MusicDetails details = 2;</code>
   */
  com.thunderclouddev.playstoreapi.proto.MusicDetails getDetails();
  /**
   * <code>optional .MusicDetails details = 2;</code>
   */
  com.thunderclouddev.playstoreapi.proto.MusicDetailsOrBuilder getDetailsOrBuilder();

  /**
   * <code>optional .ArtistDetails displayArtist = 3;</code>
   */
  boolean hasDisplayArtist();
  /**
   * <code>optional .ArtistDetails displayArtist = 3;</code>
   */
  com.thunderclouddev.playstoreapi.proto.ArtistDetails getDisplayArtist();
  /**
   * <code>optional .ArtistDetails displayArtist = 3;</code>
   */
  com.thunderclouddev.playstoreapi.proto.ArtistDetailsOrBuilder getDisplayArtistOrBuilder();
}
