/*
 * Copyright (c) 2017.
 * Distributed under the GNU GPLv3 by David Whitman.
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This source code is made available to help others learn. Please don't clone my app.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

public interface AndroidUsageStatsReportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AndroidUsageStatsReport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 androidId = 1;</code>
   */
  boolean hasAndroidId();
  /**
   * <code>optional int64 androidId = 1;</code>
   */
  long getAndroidId();

  /**
   * <code>optional int64 loggingId = 2;</code>
   */
  boolean hasLoggingId();
  /**
   * <code>optional int64 loggingId = 2;</code>
   */
  long getLoggingId();

  /**
   * <code>optional .UsageStatsExtensionProto usageStats = 3;</code>
   */
  boolean hasUsageStats();
  /**
   * <code>optional .UsageStatsExtensionProto usageStats = 3;</code>
   */
  com.thunderclouddev.playstoreapi.proto.UsageStatsExtensionProto getUsageStats();
  /**
   * <code>optional .UsageStatsExtensionProto usageStats = 3;</code>
   */
  com.thunderclouddev.playstoreapi.proto.UsageStatsExtensionProtoOrBuilder getUsageStatsOrBuilder();
}
