/*
 * Copyright (c) 2017.
 * Distributed under the GNU GPLv3 by David Whitman.
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This source code is made available to help others learn. Please don't clone my app.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

/**
 * Protobuf type {@code AndroidDataUsageProto}
 */
public final class AndroidDataUsageProto extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:AndroidDataUsageProto)
    AndroidDataUsageProtoOrBuilder {
  // Use AndroidDataUsageProto.newBuilder() to construct.
  private AndroidDataUsageProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private AndroidDataUsageProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final AndroidDataUsageProto defaultInstance;
  public static AndroidDataUsageProto getDefaultInstance() {
    return defaultInstance;
  }

  public AndroidDataUsageProto getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private AndroidDataUsageProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            version_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            currentReportMsec_ = input.readInt64();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              keyToPackageNameMapping_ = new java.util.ArrayList<com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping>();
              mutable_bitField0_ |= 0x00000004;
            }
            keyToPackageNameMapping_.add(input.readMessage(com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping.PARSER, extensionRegistry));
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              payloadLevelAppStat_ = new java.util.ArrayList<com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat>();
              mutable_bitField0_ |= 0x00000008;
            }
            payloadLevelAppStat_.add(input.readMessage(com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat.PARSER, extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              ipLayerNetworkStat_ = new java.util.ArrayList<com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat>();
              mutable_bitField0_ |= 0x00000010;
            }
            ipLayerNetworkStat_.add(input.readMessage(com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        keyToPackageNameMapping_ = java.util.Collections.unmodifiableList(keyToPackageNameMapping_);
      }
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        payloadLevelAppStat_ = java.util.Collections.unmodifiableList(payloadLevelAppStat_);
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        ipLayerNetworkStat_ = java.util.Collections.unmodifiableList(ipLayerNetworkStat_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GooglePlay.internal_static_AndroidDataUsageProto_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GooglePlay.internal_static_AndroidDataUsageProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AndroidDataUsageProto.class, Builder.class);
  }

  public static com.google.protobuf.Parser<AndroidDataUsageProto> PARSER =
      new com.google.protobuf.AbstractParser<AndroidDataUsageProto>() {
    public AndroidDataUsageProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AndroidDataUsageProto(input, extensionRegistry);
    }
  };

  @Override
  public com.google.protobuf.Parser<AndroidDataUsageProto> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>optional int32 version = 1;</code>
   */
  public boolean hasVersion() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional int32 version = 1;</code>
   */
  public int getVersion() {
    return version_;
  }

  public static final int CURRENTREPORTMSEC_FIELD_NUMBER = 2;
  private long currentReportMsec_;
  /**
   * <code>optional int64 currentReportMsec = 2;</code>
   */
  public boolean hasCurrentReportMsec() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional int64 currentReportMsec = 2;</code>
   */
  public long getCurrentReportMsec() {
    return currentReportMsec_;
  }

  public static final int KEYTOPACKAGENAMEMAPPING_FIELD_NUMBER = 3;
  private java.util.List<com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping> keyToPackageNameMapping_;
  /**
   * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
   */
  public java.util.List<com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping> getKeyToPackageNameMappingList() {
    return keyToPackageNameMapping_;
  }
  /**
   * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
   */
  public java.util.List<? extends com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMappingOrBuilder>
      getKeyToPackageNameMappingOrBuilderList() {
    return keyToPackageNameMapping_;
  }
  /**
   * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
   */
  public int getKeyToPackageNameMappingCount() {
    return keyToPackageNameMapping_.size();
  }
  /**
   * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
   */
  public com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping getKeyToPackageNameMapping(int index) {
    return keyToPackageNameMapping_.get(index);
  }
  /**
   * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
   */
  public com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMappingOrBuilder getKeyToPackageNameMappingOrBuilder(
      int index) {
    return keyToPackageNameMapping_.get(index);
  }

  public static final int PAYLOADLEVELAPPSTAT_FIELD_NUMBER = 4;
  private java.util.List<com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat> payloadLevelAppStat_;
  /**
   * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
   */
  public java.util.List<com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat> getPayloadLevelAppStatList() {
    return payloadLevelAppStat_;
  }
  /**
   * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
   */
  public java.util.List<? extends com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStatOrBuilder>
      getPayloadLevelAppStatOrBuilderList() {
    return payloadLevelAppStat_;
  }
  /**
   * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
   */
  public int getPayloadLevelAppStatCount() {
    return payloadLevelAppStat_.size();
  }
  /**
   * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
   */
  public com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat getPayloadLevelAppStat(int index) {
    return payloadLevelAppStat_.get(index);
  }
  /**
   * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
   */
  public com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStatOrBuilder getPayloadLevelAppStatOrBuilder(
      int index) {
    return payloadLevelAppStat_.get(index);
  }

  public static final int IPLAYERNETWORKSTAT_FIELD_NUMBER = 5;
  private java.util.List<com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat> ipLayerNetworkStat_;
  /**
   * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
   */
  public java.util.List<com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat> getIpLayerNetworkStatList() {
    return ipLayerNetworkStat_;
  }
  /**
   * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
   */
  public java.util.List<? extends com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStatOrBuilder>
      getIpLayerNetworkStatOrBuilderList() {
    return ipLayerNetworkStat_;
  }
  /**
   * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
   */
  public int getIpLayerNetworkStatCount() {
    return ipLayerNetworkStat_.size();
  }
  /**
   * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
   */
  public com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat getIpLayerNetworkStat(int index) {
    return ipLayerNetworkStat_.get(index);
  }
  /**
   * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
   */
  public com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStatOrBuilder getIpLayerNetworkStatOrBuilder(
      int index) {
    return ipLayerNetworkStat_.get(index);
  }

  private void initFields() {
    version_ = 0;
    currentReportMsec_ = 0L;
    keyToPackageNameMapping_ = java.util.Collections.emptyList();
    payloadLevelAppStat_ = java.util.Collections.emptyList();
    ipLayerNetworkStat_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, version_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt64(2, currentReportMsec_);
    }
    for (int i = 0; i < keyToPackageNameMapping_.size(); i++) {
      output.writeMessage(3, keyToPackageNameMapping_.get(i));
    }
    for (int i = 0; i < payloadLevelAppStat_.size(); i++) {
      output.writeMessage(4, payloadLevelAppStat_.get(i));
    }
    for (int i = 0; i < ipLayerNetworkStat_.size(); i++) {
      output.writeMessage(5, ipLayerNetworkStat_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, currentReportMsec_);
    }
    for (int i = 0; i < keyToPackageNameMapping_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, keyToPackageNameMapping_.get(i));
    }
    for (int i = 0; i < payloadLevelAppStat_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, payloadLevelAppStat_.get(i));
    }
    for (int i = 0; i < ipLayerNetworkStat_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, ipLayerNetworkStat_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  protected Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static AndroidDataUsageProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AndroidDataUsageProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AndroidDataUsageProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AndroidDataUsageProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AndroidDataUsageProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static AndroidDataUsageProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static AndroidDataUsageProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static AndroidDataUsageProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static AndroidDataUsageProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static AndroidDataUsageProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(AndroidDataUsageProto prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AndroidDataUsageProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AndroidDataUsageProto)
      com.thunderclouddev.playstoreapi.proto.AndroidDataUsageProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GooglePlay.internal_static_AndroidDataUsageProto_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GooglePlay.internal_static_AndroidDataUsageProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AndroidDataUsageProto.class, Builder.class);
    }

    // Construct using com.thunderclouddev.playstoreapi.proto.AndroidDataUsageProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getKeyToPackageNameMappingFieldBuilder();
        getPayloadLevelAppStatFieldBuilder();
        getIpLayerNetworkStatFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      version_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      currentReportMsec_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      if (keyToPackageNameMappingBuilder_ == null) {
        keyToPackageNameMapping_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        keyToPackageNameMappingBuilder_.clear();
      }
      if (payloadLevelAppStatBuilder_ == null) {
        payloadLevelAppStat_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        payloadLevelAppStatBuilder_.clear();
      }
      if (ipLayerNetworkStatBuilder_ == null) {
        ipLayerNetworkStat_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        ipLayerNetworkStatBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GooglePlay.internal_static_AndroidDataUsageProto_descriptor;
    }

    public AndroidDataUsageProto getDefaultInstanceForType() {
      return AndroidDataUsageProto.getDefaultInstance();
    }

    public AndroidDataUsageProto build() {
      AndroidDataUsageProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public AndroidDataUsageProto buildPartial() {
      AndroidDataUsageProto result = new AndroidDataUsageProto(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.version_ = version_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.currentReportMsec_ = currentReportMsec_;
      if (keyToPackageNameMappingBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          keyToPackageNameMapping_ = java.util.Collections.unmodifiableList(keyToPackageNameMapping_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.keyToPackageNameMapping_ = keyToPackageNameMapping_;
      } else {
        result.keyToPackageNameMapping_ = keyToPackageNameMappingBuilder_.build();
      }
      if (payloadLevelAppStatBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          payloadLevelAppStat_ = java.util.Collections.unmodifiableList(payloadLevelAppStat_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.payloadLevelAppStat_ = payloadLevelAppStat_;
      } else {
        result.payloadLevelAppStat_ = payloadLevelAppStatBuilder_.build();
      }
      if (ipLayerNetworkStatBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          ipLayerNetworkStat_ = java.util.Collections.unmodifiableList(ipLayerNetworkStat_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.ipLayerNetworkStat_ = ipLayerNetworkStat_;
      } else {
        result.ipLayerNetworkStat_ = ipLayerNetworkStatBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AndroidDataUsageProto) {
        return mergeFrom((AndroidDataUsageProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AndroidDataUsageProto other) {
      if (other == AndroidDataUsageProto.getDefaultInstance()) return this;
      if (other.hasVersion()) {
        setVersion(other.getVersion());
      }
      if (other.hasCurrentReportMsec()) {
        setCurrentReportMsec(other.getCurrentReportMsec());
      }
      if (keyToPackageNameMappingBuilder_ == null) {
        if (!other.keyToPackageNameMapping_.isEmpty()) {
          if (keyToPackageNameMapping_.isEmpty()) {
            keyToPackageNameMapping_ = other.keyToPackageNameMapping_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureKeyToPackageNameMappingIsMutable();
            keyToPackageNameMapping_.addAll(other.keyToPackageNameMapping_);
          }
          onChanged();
        }
      } else {
        if (!other.keyToPackageNameMapping_.isEmpty()) {
          if (keyToPackageNameMappingBuilder_.isEmpty()) {
            keyToPackageNameMappingBuilder_.dispose();
            keyToPackageNameMappingBuilder_ = null;
            keyToPackageNameMapping_ = other.keyToPackageNameMapping_;
            bitField0_ = (bitField0_ & ~0x00000004);
            keyToPackageNameMappingBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getKeyToPackageNameMappingFieldBuilder() : null;
          } else {
            keyToPackageNameMappingBuilder_.addAllMessages(other.keyToPackageNameMapping_);
          }
        }
      }
      if (payloadLevelAppStatBuilder_ == null) {
        if (!other.payloadLevelAppStat_.isEmpty()) {
          if (payloadLevelAppStat_.isEmpty()) {
            payloadLevelAppStat_ = other.payloadLevelAppStat_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePayloadLevelAppStatIsMutable();
            payloadLevelAppStat_.addAll(other.payloadLevelAppStat_);
          }
          onChanged();
        }
      } else {
        if (!other.payloadLevelAppStat_.isEmpty()) {
          if (payloadLevelAppStatBuilder_.isEmpty()) {
            payloadLevelAppStatBuilder_.dispose();
            payloadLevelAppStatBuilder_ = null;
            payloadLevelAppStat_ = other.payloadLevelAppStat_;
            bitField0_ = (bitField0_ & ~0x00000008);
            payloadLevelAppStatBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getPayloadLevelAppStatFieldBuilder() : null;
          } else {
            payloadLevelAppStatBuilder_.addAllMessages(other.payloadLevelAppStat_);
          }
        }
      }
      if (ipLayerNetworkStatBuilder_ == null) {
        if (!other.ipLayerNetworkStat_.isEmpty()) {
          if (ipLayerNetworkStat_.isEmpty()) {
            ipLayerNetworkStat_ = other.ipLayerNetworkStat_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureIpLayerNetworkStatIsMutable();
            ipLayerNetworkStat_.addAll(other.ipLayerNetworkStat_);
          }
          onChanged();
        }
      } else {
        if (!other.ipLayerNetworkStat_.isEmpty()) {
          if (ipLayerNetworkStatBuilder_.isEmpty()) {
            ipLayerNetworkStatBuilder_.dispose();
            ipLayerNetworkStatBuilder_ = null;
            ipLayerNetworkStat_ = other.ipLayerNetworkStat_;
            bitField0_ = (bitField0_ & ~0x00000010);
            ipLayerNetworkStatBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getIpLayerNetworkStatFieldBuilder() : null;
          } else {
            ipLayerNetworkStatBuilder_.addAllMessages(other.ipLayerNetworkStat_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      AndroidDataUsageProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (AndroidDataUsageProto) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int version_ ;
    /**
     * <code>optional int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>optional int32 version = 1;</code>
     */
    public Builder setVersion(int value) {
      bitField0_ |= 0x00000001;
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 version = 1;</code>
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = 0;
      onChanged();
      return this;
    }

    private long currentReportMsec_ ;
    /**
     * <code>optional int64 currentReportMsec = 2;</code>
     */
    public boolean hasCurrentReportMsec() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 currentReportMsec = 2;</code>
     */
    public long getCurrentReportMsec() {
      return currentReportMsec_;
    }
    /**
     * <code>optional int64 currentReportMsec = 2;</code>
     */
    public Builder setCurrentReportMsec(long value) {
      bitField0_ |= 0x00000002;
      currentReportMsec_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 currentReportMsec = 2;</code>
     */
    public Builder clearCurrentReportMsec() {
      bitField0_ = (bitField0_ & ~0x00000002);
      currentReportMsec_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping> keyToPackageNameMapping_ =
      java.util.Collections.emptyList();
    private void ensureKeyToPackageNameMappingIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        keyToPackageNameMapping_ = new java.util.ArrayList<com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping>(keyToPackageNameMapping_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping, com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping.Builder, com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMappingOrBuilder> keyToPackageNameMappingBuilder_;

    /**
     * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
     */
    public java.util.List<com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping> getKeyToPackageNameMappingList() {
      if (keyToPackageNameMappingBuilder_ == null) {
        return java.util.Collections.unmodifiableList(keyToPackageNameMapping_);
      } else {
        return keyToPackageNameMappingBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
     */
    public int getKeyToPackageNameMappingCount() {
      if (keyToPackageNameMappingBuilder_ == null) {
        return keyToPackageNameMapping_.size();
      } else {
        return keyToPackageNameMappingBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping getKeyToPackageNameMapping(int index) {
      if (keyToPackageNameMappingBuilder_ == null) {
        return keyToPackageNameMapping_.get(index);
      } else {
        return keyToPackageNameMappingBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
     */
    public Builder setKeyToPackageNameMapping(
        int index, com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping value) {
      if (keyToPackageNameMappingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeyToPackageNameMappingIsMutable();
        keyToPackageNameMapping_.set(index, value);
        onChanged();
      } else {
        keyToPackageNameMappingBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
     */
    public Builder setKeyToPackageNameMapping(
        int index, com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping.Builder builderForValue) {
      if (keyToPackageNameMappingBuilder_ == null) {
        ensureKeyToPackageNameMappingIsMutable();
        keyToPackageNameMapping_.set(index, builderForValue.build());
        onChanged();
      } else {
        keyToPackageNameMappingBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
     */
    public Builder addKeyToPackageNameMapping(com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping value) {
      if (keyToPackageNameMappingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeyToPackageNameMappingIsMutable();
        keyToPackageNameMapping_.add(value);
        onChanged();
      } else {
        keyToPackageNameMappingBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
     */
    public Builder addKeyToPackageNameMapping(
        int index, com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping value) {
      if (keyToPackageNameMappingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeyToPackageNameMappingIsMutable();
        keyToPackageNameMapping_.add(index, value);
        onChanged();
      } else {
        keyToPackageNameMappingBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
     */
    public Builder addKeyToPackageNameMapping(
        com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping.Builder builderForValue) {
      if (keyToPackageNameMappingBuilder_ == null) {
        ensureKeyToPackageNameMappingIsMutable();
        keyToPackageNameMapping_.add(builderForValue.build());
        onChanged();
      } else {
        keyToPackageNameMappingBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
     */
    public Builder addKeyToPackageNameMapping(
        int index, com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping.Builder builderForValue) {
      if (keyToPackageNameMappingBuilder_ == null) {
        ensureKeyToPackageNameMappingIsMutable();
        keyToPackageNameMapping_.add(index, builderForValue.build());
        onChanged();
      } else {
        keyToPackageNameMappingBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
     */
    public Builder addAllKeyToPackageNameMapping(
        Iterable<? extends com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping> values) {
      if (keyToPackageNameMappingBuilder_ == null) {
        ensureKeyToPackageNameMappingIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, keyToPackageNameMapping_);
        onChanged();
      } else {
        keyToPackageNameMappingBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
     */
    public Builder clearKeyToPackageNameMapping() {
      if (keyToPackageNameMappingBuilder_ == null) {
        keyToPackageNameMapping_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        keyToPackageNameMappingBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
     */
    public Builder removeKeyToPackageNameMapping(int index) {
      if (keyToPackageNameMappingBuilder_ == null) {
        ensureKeyToPackageNameMappingIsMutable();
        keyToPackageNameMapping_.remove(index);
        onChanged();
      } else {
        keyToPackageNameMappingBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping.Builder getKeyToPackageNameMappingBuilder(
        int index) {
      return getKeyToPackageNameMappingFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMappingOrBuilder getKeyToPackageNameMappingOrBuilder(
        int index) {
      if (keyToPackageNameMappingBuilder_ == null) {
        return keyToPackageNameMapping_.get(index);  } else {
        return keyToPackageNameMappingBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
     */
    public java.util.List<? extends com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMappingOrBuilder>
         getKeyToPackageNameMappingOrBuilderList() {
      if (keyToPackageNameMappingBuilder_ != null) {
        return keyToPackageNameMappingBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(keyToPackageNameMapping_);
      }
    }
    /**
     * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping.Builder addKeyToPackageNameMappingBuilder() {
      return getKeyToPackageNameMappingFieldBuilder().addBuilder(
          com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping.getDefaultInstance());
    }
    /**
     * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping.Builder addKeyToPackageNameMappingBuilder(
        int index) {
      return getKeyToPackageNameMappingFieldBuilder().addBuilder(
          index, com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping.getDefaultInstance());
    }
    /**
     * <code>repeated .KeyToPackageNameMapping keyToPackageNameMapping = 3;</code>
     */
    public java.util.List<com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping.Builder>
         getKeyToPackageNameMappingBuilderList() {
      return getKeyToPackageNameMappingFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping, com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping.Builder, com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMappingOrBuilder>
        getKeyToPackageNameMappingFieldBuilder() {
      if (keyToPackageNameMappingBuilder_ == null) {
        keyToPackageNameMappingBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping, com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMapping.Builder, com.thunderclouddev.playstoreapi.proto.KeyToPackageNameMappingOrBuilder>(
                keyToPackageNameMapping_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        keyToPackageNameMapping_ = null;
      }
      return keyToPackageNameMappingBuilder_;
    }

    private java.util.List<com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat> payloadLevelAppStat_ =
      java.util.Collections.emptyList();
    private void ensurePayloadLevelAppStatIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        payloadLevelAppStat_ = new java.util.ArrayList<com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat>(payloadLevelAppStat_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat, com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat.Builder, com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStatOrBuilder> payloadLevelAppStatBuilder_;

    /**
     * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
     */
    public java.util.List<com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat> getPayloadLevelAppStatList() {
      if (payloadLevelAppStatBuilder_ == null) {
        return java.util.Collections.unmodifiableList(payloadLevelAppStat_);
      } else {
        return payloadLevelAppStatBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
     */
    public int getPayloadLevelAppStatCount() {
      if (payloadLevelAppStatBuilder_ == null) {
        return payloadLevelAppStat_.size();
      } else {
        return payloadLevelAppStatBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat getPayloadLevelAppStat(int index) {
      if (payloadLevelAppStatBuilder_ == null) {
        return payloadLevelAppStat_.get(index);
      } else {
        return payloadLevelAppStatBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
     */
    public Builder setPayloadLevelAppStat(
        int index, com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat value) {
      if (payloadLevelAppStatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayloadLevelAppStatIsMutable();
        payloadLevelAppStat_.set(index, value);
        onChanged();
      } else {
        payloadLevelAppStatBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
     */
    public Builder setPayloadLevelAppStat(
        int index, com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat.Builder builderForValue) {
      if (payloadLevelAppStatBuilder_ == null) {
        ensurePayloadLevelAppStatIsMutable();
        payloadLevelAppStat_.set(index, builderForValue.build());
        onChanged();
      } else {
        payloadLevelAppStatBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
     */
    public Builder addPayloadLevelAppStat(com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat value) {
      if (payloadLevelAppStatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayloadLevelAppStatIsMutable();
        payloadLevelAppStat_.add(value);
        onChanged();
      } else {
        payloadLevelAppStatBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
     */
    public Builder addPayloadLevelAppStat(
        int index, com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat value) {
      if (payloadLevelAppStatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayloadLevelAppStatIsMutable();
        payloadLevelAppStat_.add(index, value);
        onChanged();
      } else {
        payloadLevelAppStatBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
     */
    public Builder addPayloadLevelAppStat(
        com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat.Builder builderForValue) {
      if (payloadLevelAppStatBuilder_ == null) {
        ensurePayloadLevelAppStatIsMutable();
        payloadLevelAppStat_.add(builderForValue.build());
        onChanged();
      } else {
        payloadLevelAppStatBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
     */
    public Builder addPayloadLevelAppStat(
        int index, com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat.Builder builderForValue) {
      if (payloadLevelAppStatBuilder_ == null) {
        ensurePayloadLevelAppStatIsMutable();
        payloadLevelAppStat_.add(index, builderForValue.build());
        onChanged();
      } else {
        payloadLevelAppStatBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
     */
    public Builder addAllPayloadLevelAppStat(
        Iterable<? extends com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat> values) {
      if (payloadLevelAppStatBuilder_ == null) {
        ensurePayloadLevelAppStatIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, payloadLevelAppStat_);
        onChanged();
      } else {
        payloadLevelAppStatBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
     */
    public Builder clearPayloadLevelAppStat() {
      if (payloadLevelAppStatBuilder_ == null) {
        payloadLevelAppStat_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        payloadLevelAppStatBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
     */
    public Builder removePayloadLevelAppStat(int index) {
      if (payloadLevelAppStatBuilder_ == null) {
        ensurePayloadLevelAppStatIsMutable();
        payloadLevelAppStat_.remove(index);
        onChanged();
      } else {
        payloadLevelAppStatBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat.Builder getPayloadLevelAppStatBuilder(
        int index) {
      return getPayloadLevelAppStatFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStatOrBuilder getPayloadLevelAppStatOrBuilder(
        int index) {
      if (payloadLevelAppStatBuilder_ == null) {
        return payloadLevelAppStat_.get(index);  } else {
        return payloadLevelAppStatBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
     */
    public java.util.List<? extends com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStatOrBuilder>
         getPayloadLevelAppStatOrBuilderList() {
      if (payloadLevelAppStatBuilder_ != null) {
        return payloadLevelAppStatBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(payloadLevelAppStat_);
      }
    }
    /**
     * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat.Builder addPayloadLevelAppStatBuilder() {
      return getPayloadLevelAppStatFieldBuilder().addBuilder(
          com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat.getDefaultInstance());
    }
    /**
     * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat.Builder addPayloadLevelAppStatBuilder(
        int index) {
      return getPayloadLevelAppStatFieldBuilder().addBuilder(
          index, com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat.getDefaultInstance());
    }
    /**
     * <code>repeated .PayloadLevelAppStat payloadLevelAppStat = 4;</code>
     */
    public java.util.List<com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat.Builder>
         getPayloadLevelAppStatBuilderList() {
      return getPayloadLevelAppStatFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat, com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat.Builder, com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStatOrBuilder>
        getPayloadLevelAppStatFieldBuilder() {
      if (payloadLevelAppStatBuilder_ == null) {
        payloadLevelAppStatBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat, com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStat.Builder, com.thunderclouddev.playstoreapi.proto.PayloadLevelAppStatOrBuilder>(
                payloadLevelAppStat_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        payloadLevelAppStat_ = null;
      }
      return payloadLevelAppStatBuilder_;
    }

    private java.util.List<com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat> ipLayerNetworkStat_ =
      java.util.Collections.emptyList();
    private void ensureIpLayerNetworkStatIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        ipLayerNetworkStat_ = new java.util.ArrayList<com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat>(ipLayerNetworkStat_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat, com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat.Builder, com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStatOrBuilder> ipLayerNetworkStatBuilder_;

    /**
     * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
     */
    public java.util.List<com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat> getIpLayerNetworkStatList() {
      if (ipLayerNetworkStatBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ipLayerNetworkStat_);
      } else {
        return ipLayerNetworkStatBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
     */
    public int getIpLayerNetworkStatCount() {
      if (ipLayerNetworkStatBuilder_ == null) {
        return ipLayerNetworkStat_.size();
      } else {
        return ipLayerNetworkStatBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat getIpLayerNetworkStat(int index) {
      if (ipLayerNetworkStatBuilder_ == null) {
        return ipLayerNetworkStat_.get(index);
      } else {
        return ipLayerNetworkStatBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
     */
    public Builder setIpLayerNetworkStat(
        int index, com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat value) {
      if (ipLayerNetworkStatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIpLayerNetworkStatIsMutable();
        ipLayerNetworkStat_.set(index, value);
        onChanged();
      } else {
        ipLayerNetworkStatBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
     */
    public Builder setIpLayerNetworkStat(
        int index, com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat.Builder builderForValue) {
      if (ipLayerNetworkStatBuilder_ == null) {
        ensureIpLayerNetworkStatIsMutable();
        ipLayerNetworkStat_.set(index, builderForValue.build());
        onChanged();
      } else {
        ipLayerNetworkStatBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
     */
    public Builder addIpLayerNetworkStat(com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat value) {
      if (ipLayerNetworkStatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIpLayerNetworkStatIsMutable();
        ipLayerNetworkStat_.add(value);
        onChanged();
      } else {
        ipLayerNetworkStatBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
     */
    public Builder addIpLayerNetworkStat(
        int index, com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat value) {
      if (ipLayerNetworkStatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIpLayerNetworkStatIsMutable();
        ipLayerNetworkStat_.add(index, value);
        onChanged();
      } else {
        ipLayerNetworkStatBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
     */
    public Builder addIpLayerNetworkStat(
        com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat.Builder builderForValue) {
      if (ipLayerNetworkStatBuilder_ == null) {
        ensureIpLayerNetworkStatIsMutable();
        ipLayerNetworkStat_.add(builderForValue.build());
        onChanged();
      } else {
        ipLayerNetworkStatBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
     */
    public Builder addIpLayerNetworkStat(
        int index, com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat.Builder builderForValue) {
      if (ipLayerNetworkStatBuilder_ == null) {
        ensureIpLayerNetworkStatIsMutable();
        ipLayerNetworkStat_.add(index, builderForValue.build());
        onChanged();
      } else {
        ipLayerNetworkStatBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
     */
    public Builder addAllIpLayerNetworkStat(
        Iterable<? extends com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat> values) {
      if (ipLayerNetworkStatBuilder_ == null) {
        ensureIpLayerNetworkStatIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ipLayerNetworkStat_);
        onChanged();
      } else {
        ipLayerNetworkStatBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
     */
    public Builder clearIpLayerNetworkStat() {
      if (ipLayerNetworkStatBuilder_ == null) {
        ipLayerNetworkStat_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        ipLayerNetworkStatBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
     */
    public Builder removeIpLayerNetworkStat(int index) {
      if (ipLayerNetworkStatBuilder_ == null) {
        ensureIpLayerNetworkStatIsMutable();
        ipLayerNetworkStat_.remove(index);
        onChanged();
      } else {
        ipLayerNetworkStatBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat.Builder getIpLayerNetworkStatBuilder(
        int index) {
      return getIpLayerNetworkStatFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStatOrBuilder getIpLayerNetworkStatOrBuilder(
        int index) {
      if (ipLayerNetworkStatBuilder_ == null) {
        return ipLayerNetworkStat_.get(index);  } else {
        return ipLayerNetworkStatBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
     */
    public java.util.List<? extends com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStatOrBuilder>
         getIpLayerNetworkStatOrBuilderList() {
      if (ipLayerNetworkStatBuilder_ != null) {
        return ipLayerNetworkStatBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ipLayerNetworkStat_);
      }
    }
    /**
     * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat.Builder addIpLayerNetworkStatBuilder() {
      return getIpLayerNetworkStatFieldBuilder().addBuilder(
          com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat.getDefaultInstance());
    }
    /**
     * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat.Builder addIpLayerNetworkStatBuilder(
        int index) {
      return getIpLayerNetworkStatFieldBuilder().addBuilder(
          index, com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat.getDefaultInstance());
    }
    /**
     * <code>repeated .IpLayerNetworkStat ipLayerNetworkStat = 5;</code>
     */
    public java.util.List<com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat.Builder>
         getIpLayerNetworkStatBuilderList() {
      return getIpLayerNetworkStatFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat, com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat.Builder, com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStatOrBuilder>
        getIpLayerNetworkStatFieldBuilder() {
      if (ipLayerNetworkStatBuilder_ == null) {
        ipLayerNetworkStatBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat, com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat.Builder, com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStatOrBuilder>(
                ipLayerNetworkStat_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        ipLayerNetworkStat_ = null;
      }
      return ipLayerNetworkStatBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:AndroidDataUsageProto)
  }

  static {
    defaultInstance = new AndroidDataUsageProto(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:AndroidDataUsageProto)
}

