/*
 * Copyright (c) 2017.
 * Distributed under the GNU GPLv3 by David Whitman.
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This source code is made available to help others learn. Please don't clone my app.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

public interface AndroidCheckinResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AndroidCheckinResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool statsOk = 1;</code>
   */
  boolean hasStatsOk();
  /**
   * <code>optional bool statsOk = 1;</code>
   */
  boolean getStatsOk();

  /**
   * <code>repeated .AndroidIntentProto intent = 2;</code>
   */
  java.util.List<com.thunderclouddev.playstoreapi.proto.AndroidIntentProto>
      getIntentList();
  /**
   * <code>repeated .AndroidIntentProto intent = 2;</code>
   */
  com.thunderclouddev.playstoreapi.proto.AndroidIntentProto getIntent(int index);
  /**
   * <code>repeated .AndroidIntentProto intent = 2;</code>
   */
  int getIntentCount();
  /**
   * <code>repeated .AndroidIntentProto intent = 2;</code>
   */
  java.util.List<? extends com.thunderclouddev.playstoreapi.proto.AndroidIntentProtoOrBuilder>
      getIntentOrBuilderList();
  /**
   * <code>repeated .AndroidIntentProto intent = 2;</code>
   */
  com.thunderclouddev.playstoreapi.proto.AndroidIntentProtoOrBuilder getIntentOrBuilder(int index);

  /**
   * <code>optional int64 timeMsec = 3;</code>
   */
  boolean hasTimeMsec();
  /**
   * <code>optional int64 timeMsec = 3;</code>
   */
  long getTimeMsec();

  /**
   * <code>optional string digest = 4;</code>
   */
  boolean hasDigest();
  /**
   * <code>optional string digest = 4;</code>
   */
  String getDigest();
  /**
   * <code>optional string digest = 4;</code>
   */
  com.google.protobuf.ByteString
      getDigestBytes();

  /**
   * <code>repeated .GservicesSetting setting = 5;</code>
   */
  java.util.List<com.thunderclouddev.playstoreapi.proto.GservicesSetting>
      getSettingList();
  /**
   * <code>repeated .GservicesSetting setting = 5;</code>
   */
  com.thunderclouddev.playstoreapi.proto.GservicesSetting getSetting(int index);
  /**
   * <code>repeated .GservicesSetting setting = 5;</code>
   */
  int getSettingCount();
  /**
   * <code>repeated .GservicesSetting setting = 5;</code>
   */
  java.util.List<? extends com.thunderclouddev.playstoreapi.proto.GservicesSettingOrBuilder>
      getSettingOrBuilderList();
  /**
   * <code>repeated .GservicesSetting setting = 5;</code>
   */
  com.thunderclouddev.playstoreapi.proto.GservicesSettingOrBuilder getSettingOrBuilder(int index);

  /**
   * <code>optional bool marketOk = 6;</code>
   */
  boolean hasMarketOk();
  /**
   * <code>optional bool marketOk = 6;</code>
   */
  boolean getMarketOk();

  /**
   * <code>optional fixed64 androidId = 7;</code>
   */
  boolean hasAndroidId();
  /**
   * <code>optional fixed64 androidId = 7;</code>
   */
  long getAndroidId();

  /**
   * <code>optional fixed64 securityToken = 8;</code>
   */
  boolean hasSecurityToken();
  /**
   * <code>optional fixed64 securityToken = 8;</code>
   */
  long getSecurityToken();

  /**
   * <code>optional bool settingsDiff = 9;</code>
   */
  boolean hasSettingsDiff();
  /**
   * <code>optional bool settingsDiff = 9;</code>
   */
  boolean getSettingsDiff();

  /**
   * <code>repeated string deleteSetting = 10;</code>
   */
  com.google.protobuf.ProtocolStringList
      getDeleteSettingList();
  /**
   * <code>repeated string deleteSetting = 10;</code>
   */
  int getDeleteSettingCount();
  /**
   * <code>repeated string deleteSetting = 10;</code>
   */
  String getDeleteSetting(int index);
  /**
   * <code>repeated string deleteSetting = 10;</code>
   */
  com.google.protobuf.ByteString
      getDeleteSettingBytes(int index);
}
