/*
 * Copyright (c) 2017.
 * Distributed under the GNU GPLv3 by David Whitman.
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This source code is made available to help others learn. Please don't clone my app.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

public interface BookSubjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BookSubject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   */
  String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string query = 2;</code>
   */
  boolean hasQuery();
  /**
   * <code>optional string query = 2;</code>
   */
  String getQuery();
  /**
   * <code>optional string query = 2;</code>
   */
  com.google.protobuf.ByteString
      getQueryBytes();

  /**
   * <code>optional string subjectId = 3;</code>
   */
  boolean hasSubjectId();
  /**
   * <code>optional string subjectId = 3;</code>
   */
  String getSubjectId();
  /**
   * <code>optional string subjectId = 3;</code>
   */
  com.google.protobuf.ByteString
      getSubjectIdBytes();
}
