/*
 * Copyright (c) 2017.
 * Distributed under the GNU GPLv3 by David Whitman.
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This source code is made available to help others learn. Please don't clone my app.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

public interface CarrierTosEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CarrierTosEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string url = 1;</code>
   */
  boolean hasUrl();
  /**
   * <code>optional string url = 1;</code>
   */
  String getUrl();
  /**
   * <code>optional string url = 1;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>optional string version = 2;</code>
   */
  boolean hasVersion();
  /**
   * <code>optional string version = 2;</code>
   */
  String getVersion();
  /**
   * <code>optional string version = 2;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
