/*
 * Copyright (c) 2017.
 * Distributed under the GNU GPLv3 by David Whitman.
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This source code is made available to help others learn. Please don't clone my app.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

/**
 * Protobuf type {@code CreditCardInstrument}
 */
public final class CreditCardInstrument extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:CreditCardInstrument)
    CreditCardInstrumentOrBuilder {
  // Use CreditCardInstrument.newBuilder() to construct.
  private CreditCardInstrument(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private CreditCardInstrument(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final CreditCardInstrument defaultInstance;
  public static CreditCardInstrument getDefaultInstance() {
    return defaultInstance;
  }

  public CreditCardInstrument getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private CreditCardInstrument(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            type_ = input.readInt32();
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            escrowHandle_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            lastDigits_ = bs;
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            expirationMonth_ = input.readInt32();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            expirationYear_ = input.readInt32();
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              escrowEfeParam_ = new java.util.ArrayList<com.thunderclouddev.playstoreapi.proto.EfeParam>();
              mutable_bitField0_ |= 0x00000020;
            }
            escrowEfeParam_.add(input.readMessage(com.thunderclouddev.playstoreapi.proto.EfeParam.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        escrowEfeParam_ = java.util.Collections.unmodifiableList(escrowEfeParam_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GooglePlay.internal_static_CreditCardInstrument_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GooglePlay.internal_static_CreditCardInstrument_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CreditCardInstrument.class, Builder.class);
  }

  public static com.google.protobuf.Parser<CreditCardInstrument> PARSER =
      new com.google.protobuf.AbstractParser<CreditCardInstrument>() {
    public CreditCardInstrument parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreditCardInstrument(input, extensionRegistry);
    }
  };

  @Override
  public com.google.protobuf.Parser<CreditCardInstrument> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>optional int32 type = 1;</code>
   */
  public boolean hasType() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional int32 type = 1;</code>
   */
  public int getType() {
    return type_;
  }

  public static final int ESCROWHANDLE_FIELD_NUMBER = 2;
  private Object escrowHandle_;
  /**
   * <code>optional string escrowHandle = 2;</code>
   */
  public boolean hasEscrowHandle() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string escrowHandle = 2;</code>
   */
  public String getEscrowHandle() {
    Object ref = escrowHandle_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        escrowHandle_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string escrowHandle = 2;</code>
   */
  public com.google.protobuf.ByteString
      getEscrowHandleBytes() {
    Object ref = escrowHandle_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      escrowHandle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTDIGITS_FIELD_NUMBER = 3;
  private Object lastDigits_;
  /**
   * <code>optional string lastDigits = 3;</code>
   */
  public boolean hasLastDigits() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string lastDigits = 3;</code>
   */
  public String getLastDigits() {
    Object ref = lastDigits_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        lastDigits_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string lastDigits = 3;</code>
   */
  public com.google.protobuf.ByteString
      getLastDigitsBytes() {
    Object ref = lastDigits_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      lastDigits_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPIRATIONMONTH_FIELD_NUMBER = 4;
  private int expirationMonth_;
  /**
   * <code>optional int32 expirationMonth = 4;</code>
   */
  public boolean hasExpirationMonth() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional int32 expirationMonth = 4;</code>
   */
  public int getExpirationMonth() {
    return expirationMonth_;
  }

  public static final int EXPIRATIONYEAR_FIELD_NUMBER = 5;
  private int expirationYear_;
  /**
   * <code>optional int32 expirationYear = 5;</code>
   */
  public boolean hasExpirationYear() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional int32 expirationYear = 5;</code>
   */
  public int getExpirationYear() {
    return expirationYear_;
  }

  public static final int ESCROWEFEPARAM_FIELD_NUMBER = 6;
  private java.util.List<com.thunderclouddev.playstoreapi.proto.EfeParam> escrowEfeParam_;
  /**
   * <code>repeated .EfeParam escrowEfeParam = 6;</code>
   */
  public java.util.List<com.thunderclouddev.playstoreapi.proto.EfeParam> getEscrowEfeParamList() {
    return escrowEfeParam_;
  }
  /**
   * <code>repeated .EfeParam escrowEfeParam = 6;</code>
   */
  public java.util.List<? extends com.thunderclouddev.playstoreapi.proto.EfeParamOrBuilder>
      getEscrowEfeParamOrBuilderList() {
    return escrowEfeParam_;
  }
  /**
   * <code>repeated .EfeParam escrowEfeParam = 6;</code>
   */
  public int getEscrowEfeParamCount() {
    return escrowEfeParam_.size();
  }
  /**
   * <code>repeated .EfeParam escrowEfeParam = 6;</code>
   */
  public com.thunderclouddev.playstoreapi.proto.EfeParam getEscrowEfeParam(int index) {
    return escrowEfeParam_.get(index);
  }
  /**
   * <code>repeated .EfeParam escrowEfeParam = 6;</code>
   */
  public com.thunderclouddev.playstoreapi.proto.EfeParamOrBuilder getEscrowEfeParamOrBuilder(
      int index) {
    return escrowEfeParam_.get(index);
  }

  private void initFields() {
    type_ = 0;
    escrowHandle_ = "";
    lastDigits_ = "";
    expirationMonth_ = 0;
    expirationYear_ = 0;
    escrowEfeParam_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, type_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getEscrowHandleBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getLastDigitsBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt32(4, expirationMonth_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeInt32(5, expirationYear_);
    }
    for (int i = 0; i < escrowEfeParam_.size(); i++) {
      output.writeMessage(6, escrowEfeParam_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, type_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getEscrowHandleBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getLastDigitsBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, expirationMonth_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, expirationYear_);
    }
    for (int i = 0; i < escrowEfeParam_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, escrowEfeParam_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  protected Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static CreditCardInstrument parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CreditCardInstrument parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CreditCardInstrument parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CreditCardInstrument parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CreditCardInstrument parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static CreditCardInstrument parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static CreditCardInstrument parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static CreditCardInstrument parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static CreditCardInstrument parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static CreditCardInstrument parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(CreditCardInstrument prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CreditCardInstrument}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CreditCardInstrument)
      com.thunderclouddev.playstoreapi.proto.CreditCardInstrumentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GooglePlay.internal_static_CreditCardInstrument_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GooglePlay.internal_static_CreditCardInstrument_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CreditCardInstrument.class, Builder.class);
    }

    // Construct using com.thunderclouddev.playstoreapi.proto.CreditCardInstrument.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getEscrowEfeParamFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      type_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      escrowHandle_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      lastDigits_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      expirationMonth_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      expirationYear_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      if (escrowEfeParamBuilder_ == null) {
        escrowEfeParam_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        escrowEfeParamBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GooglePlay.internal_static_CreditCardInstrument_descriptor;
    }

    public CreditCardInstrument getDefaultInstanceForType() {
      return CreditCardInstrument.getDefaultInstance();
    }

    public CreditCardInstrument build() {
      CreditCardInstrument result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public CreditCardInstrument buildPartial() {
      CreditCardInstrument result = new CreditCardInstrument(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.type_ = type_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.escrowHandle_ = escrowHandle_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.lastDigits_ = lastDigits_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.expirationMonth_ = expirationMonth_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.expirationYear_ = expirationYear_;
      if (escrowEfeParamBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          escrowEfeParam_ = java.util.Collections.unmodifiableList(escrowEfeParam_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.escrowEfeParam_ = escrowEfeParam_;
      } else {
        result.escrowEfeParam_ = escrowEfeParamBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CreditCardInstrument) {
        return mergeFrom((CreditCardInstrument)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CreditCardInstrument other) {
      if (other == CreditCardInstrument.getDefaultInstance()) return this;
      if (other.hasType()) {
        setType(other.getType());
      }
      if (other.hasEscrowHandle()) {
        bitField0_ |= 0x00000002;
        escrowHandle_ = other.escrowHandle_;
        onChanged();
      }
      if (other.hasLastDigits()) {
        bitField0_ |= 0x00000004;
        lastDigits_ = other.lastDigits_;
        onChanged();
      }
      if (other.hasExpirationMonth()) {
        setExpirationMonth(other.getExpirationMonth());
      }
      if (other.hasExpirationYear()) {
        setExpirationYear(other.getExpirationYear());
      }
      if (escrowEfeParamBuilder_ == null) {
        if (!other.escrowEfeParam_.isEmpty()) {
          if (escrowEfeParam_.isEmpty()) {
            escrowEfeParam_ = other.escrowEfeParam_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureEscrowEfeParamIsMutable();
            escrowEfeParam_.addAll(other.escrowEfeParam_);
          }
          onChanged();
        }
      } else {
        if (!other.escrowEfeParam_.isEmpty()) {
          if (escrowEfeParamBuilder_.isEmpty()) {
            escrowEfeParamBuilder_.dispose();
            escrowEfeParamBuilder_ = null;
            escrowEfeParam_ = other.escrowEfeParam_;
            bitField0_ = (bitField0_ & ~0x00000020);
            escrowEfeParamBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getEscrowEfeParamFieldBuilder() : null;
          } else {
            escrowEfeParamBuilder_.addAllMessages(other.escrowEfeParam_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CreditCardInstrument parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CreditCardInstrument) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int type_ ;
    /**
     * <code>optional int32 type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }
    /**
     * <code>optional int32 type = 1;</code>
     */
    public Builder setType(int value) {
      bitField0_ |= 0x00000001;
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 type = 1;</code>
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private Object escrowHandle_ = "";
    /**
     * <code>optional string escrowHandle = 2;</code>
     */
    public boolean hasEscrowHandle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string escrowHandle = 2;</code>
     */
    public String getEscrowHandle() {
      Object ref = escrowHandle_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          escrowHandle_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string escrowHandle = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEscrowHandleBytes() {
      Object ref = escrowHandle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        escrowHandle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string escrowHandle = 2;</code>
     */
    public Builder setEscrowHandle(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      escrowHandle_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string escrowHandle = 2;</code>
     */
    public Builder clearEscrowHandle() {
      bitField0_ = (bitField0_ & ~0x00000002);
      escrowHandle_ = getDefaultInstance().getEscrowHandle();
      onChanged();
      return this;
    }
    /**
     * <code>optional string escrowHandle = 2;</code>
     */
    public Builder setEscrowHandleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      escrowHandle_ = value;
      onChanged();
      return this;
    }

    private Object lastDigits_ = "";
    /**
     * <code>optional string lastDigits = 3;</code>
     */
    public boolean hasLastDigits() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string lastDigits = 3;</code>
     */
    public String getLastDigits() {
      Object ref = lastDigits_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastDigits_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string lastDigits = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLastDigitsBytes() {
      Object ref = lastDigits_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        lastDigits_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string lastDigits = 3;</code>
     */
    public Builder setLastDigits(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      lastDigits_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string lastDigits = 3;</code>
     */
    public Builder clearLastDigits() {
      bitField0_ = (bitField0_ & ~0x00000004);
      lastDigits_ = getDefaultInstance().getLastDigits();
      onChanged();
      return this;
    }
    /**
     * <code>optional string lastDigits = 3;</code>
     */
    public Builder setLastDigitsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      lastDigits_ = value;
      onChanged();
      return this;
    }

    private int expirationMonth_ ;
    /**
     * <code>optional int32 expirationMonth = 4;</code>
     */
    public boolean hasExpirationMonth() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 expirationMonth = 4;</code>
     */
    public int getExpirationMonth() {
      return expirationMonth_;
    }
    /**
     * <code>optional int32 expirationMonth = 4;</code>
     */
    public Builder setExpirationMonth(int value) {
      bitField0_ |= 0x00000008;
      expirationMonth_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 expirationMonth = 4;</code>
     */
    public Builder clearExpirationMonth() {
      bitField0_ = (bitField0_ & ~0x00000008);
      expirationMonth_ = 0;
      onChanged();
      return this;
    }

    private int expirationYear_ ;
    /**
     * <code>optional int32 expirationYear = 5;</code>
     */
    public boolean hasExpirationYear() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 expirationYear = 5;</code>
     */
    public int getExpirationYear() {
      return expirationYear_;
    }
    /**
     * <code>optional int32 expirationYear = 5;</code>
     */
    public Builder setExpirationYear(int value) {
      bitField0_ |= 0x00000010;
      expirationYear_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 expirationYear = 5;</code>
     */
    public Builder clearExpirationYear() {
      bitField0_ = (bitField0_ & ~0x00000010);
      expirationYear_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.thunderclouddev.playstoreapi.proto.EfeParam> escrowEfeParam_ =
      java.util.Collections.emptyList();
    private void ensureEscrowEfeParamIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        escrowEfeParam_ = new java.util.ArrayList<com.thunderclouddev.playstoreapi.proto.EfeParam>(escrowEfeParam_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.thunderclouddev.playstoreapi.proto.EfeParam, com.thunderclouddev.playstoreapi.proto.EfeParam.Builder, com.thunderclouddev.playstoreapi.proto.EfeParamOrBuilder> escrowEfeParamBuilder_;

    /**
     * <code>repeated .EfeParam escrowEfeParam = 6;</code>
     */
    public java.util.List<com.thunderclouddev.playstoreapi.proto.EfeParam> getEscrowEfeParamList() {
      if (escrowEfeParamBuilder_ == null) {
        return java.util.Collections.unmodifiableList(escrowEfeParam_);
      } else {
        return escrowEfeParamBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .EfeParam escrowEfeParam = 6;</code>
     */
    public int getEscrowEfeParamCount() {
      if (escrowEfeParamBuilder_ == null) {
        return escrowEfeParam_.size();
      } else {
        return escrowEfeParamBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .EfeParam escrowEfeParam = 6;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.EfeParam getEscrowEfeParam(int index) {
      if (escrowEfeParamBuilder_ == null) {
        return escrowEfeParam_.get(index);
      } else {
        return escrowEfeParamBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .EfeParam escrowEfeParam = 6;</code>
     */
    public Builder setEscrowEfeParam(
        int index, com.thunderclouddev.playstoreapi.proto.EfeParam value) {
      if (escrowEfeParamBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEscrowEfeParamIsMutable();
        escrowEfeParam_.set(index, value);
        onChanged();
      } else {
        escrowEfeParamBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .EfeParam escrowEfeParam = 6;</code>
     */
    public Builder setEscrowEfeParam(
        int index, com.thunderclouddev.playstoreapi.proto.EfeParam.Builder builderForValue) {
      if (escrowEfeParamBuilder_ == null) {
        ensureEscrowEfeParamIsMutable();
        escrowEfeParam_.set(index, builderForValue.build());
        onChanged();
      } else {
        escrowEfeParamBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EfeParam escrowEfeParam = 6;</code>
     */
    public Builder addEscrowEfeParam(com.thunderclouddev.playstoreapi.proto.EfeParam value) {
      if (escrowEfeParamBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEscrowEfeParamIsMutable();
        escrowEfeParam_.add(value);
        onChanged();
      } else {
        escrowEfeParamBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .EfeParam escrowEfeParam = 6;</code>
     */
    public Builder addEscrowEfeParam(
        int index, com.thunderclouddev.playstoreapi.proto.EfeParam value) {
      if (escrowEfeParamBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEscrowEfeParamIsMutable();
        escrowEfeParam_.add(index, value);
        onChanged();
      } else {
        escrowEfeParamBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .EfeParam escrowEfeParam = 6;</code>
     */
    public Builder addEscrowEfeParam(
        com.thunderclouddev.playstoreapi.proto.EfeParam.Builder builderForValue) {
      if (escrowEfeParamBuilder_ == null) {
        ensureEscrowEfeParamIsMutable();
        escrowEfeParam_.add(builderForValue.build());
        onChanged();
      } else {
        escrowEfeParamBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EfeParam escrowEfeParam = 6;</code>
     */
    public Builder addEscrowEfeParam(
        int index, com.thunderclouddev.playstoreapi.proto.EfeParam.Builder builderForValue) {
      if (escrowEfeParamBuilder_ == null) {
        ensureEscrowEfeParamIsMutable();
        escrowEfeParam_.add(index, builderForValue.build());
        onChanged();
      } else {
        escrowEfeParamBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EfeParam escrowEfeParam = 6;</code>
     */
    public Builder addAllEscrowEfeParam(
        Iterable<? extends com.thunderclouddev.playstoreapi.proto.EfeParam> values) {
      if (escrowEfeParamBuilder_ == null) {
        ensureEscrowEfeParamIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, escrowEfeParam_);
        onChanged();
      } else {
        escrowEfeParamBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .EfeParam escrowEfeParam = 6;</code>
     */
    public Builder clearEscrowEfeParam() {
      if (escrowEfeParamBuilder_ == null) {
        escrowEfeParam_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        escrowEfeParamBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .EfeParam escrowEfeParam = 6;</code>
     */
    public Builder removeEscrowEfeParam(int index) {
      if (escrowEfeParamBuilder_ == null) {
        ensureEscrowEfeParamIsMutable();
        escrowEfeParam_.remove(index);
        onChanged();
      } else {
        escrowEfeParamBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .EfeParam escrowEfeParam = 6;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.EfeParam.Builder getEscrowEfeParamBuilder(
        int index) {
      return getEscrowEfeParamFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .EfeParam escrowEfeParam = 6;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.EfeParamOrBuilder getEscrowEfeParamOrBuilder(
        int index) {
      if (escrowEfeParamBuilder_ == null) {
        return escrowEfeParam_.get(index);  } else {
        return escrowEfeParamBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .EfeParam escrowEfeParam = 6;</code>
     */
    public java.util.List<? extends com.thunderclouddev.playstoreapi.proto.EfeParamOrBuilder>
         getEscrowEfeParamOrBuilderList() {
      if (escrowEfeParamBuilder_ != null) {
        return escrowEfeParamBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(escrowEfeParam_);
      }
    }
    /**
     * <code>repeated .EfeParam escrowEfeParam = 6;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.EfeParam.Builder addEscrowEfeParamBuilder() {
      return getEscrowEfeParamFieldBuilder().addBuilder(
          com.thunderclouddev.playstoreapi.proto.EfeParam.getDefaultInstance());
    }
    /**
     * <code>repeated .EfeParam escrowEfeParam = 6;</code>
     */
    public com.thunderclouddev.playstoreapi.proto.EfeParam.Builder addEscrowEfeParamBuilder(
        int index) {
      return getEscrowEfeParamFieldBuilder().addBuilder(
          index, com.thunderclouddev.playstoreapi.proto.EfeParam.getDefaultInstance());
    }
    /**
     * <code>repeated .EfeParam escrowEfeParam = 6;</code>
     */
    public java.util.List<com.thunderclouddev.playstoreapi.proto.EfeParam.Builder>
         getEscrowEfeParamBuilderList() {
      return getEscrowEfeParamFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.thunderclouddev.playstoreapi.proto.EfeParam, com.thunderclouddev.playstoreapi.proto.EfeParam.Builder, com.thunderclouddev.playstoreapi.proto.EfeParamOrBuilder>
        getEscrowEfeParamFieldBuilder() {
      if (escrowEfeParamBuilder_ == null) {
        escrowEfeParamBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.thunderclouddev.playstoreapi.proto.EfeParam, com.thunderclouddev.playstoreapi.proto.EfeParam.Builder, com.thunderclouddev.playstoreapi.proto.EfeParamOrBuilder>(
                escrowEfeParam_,
                ((bitField0_ & 0x00000020) == 0x00000020),
                getParentForChildren(),
                isClean());
        escrowEfeParam_ = null;
      }
      return escrowEfeParamBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:CreditCardInstrument)
  }

  static {
    defaultInstance = new CreditCardInstrument(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:CreditCardInstrument)
}

