/*
 * Copyright (c) 2017.
 * Distributed under the GNU GPLv3 by David Whitman.
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This source code is made available to help others learn. Please don't clone my app.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

public interface DocumentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Document)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .Docid docid = 1;</code>
   */
  boolean hasDocid();
  /**
   * <code>optional .Docid docid = 1;</code>
   */
  Docid getDocid();
  /**
   * <code>optional .Docid docid = 1;</code>
   */
  DocidOrBuilder getDocidOrBuilder();

  /**
   * <code>optional .Docid fetchDocid = 2;</code>
   */
  boolean hasFetchDocid();
  /**
   * <code>optional .Docid fetchDocid = 2;</code>
   */
  Docid getFetchDocid();
  /**
   * <code>optional .Docid fetchDocid = 2;</code>
   */
  DocidOrBuilder getFetchDocidOrBuilder();

  /**
   * <code>optional .Docid sampleDocid = 3;</code>
   */
  boolean hasSampleDocid();
  /**
   * <code>optional .Docid sampleDocid = 3;</code>
   */
  Docid getSampleDocid();
  /**
   * <code>optional .Docid sampleDocid = 3;</code>
   */
  DocidOrBuilder getSampleDocidOrBuilder();

  /**
   * <code>optional string title = 4;</code>
   */
  boolean hasTitle();
  /**
   * <code>optional string title = 4;</code>
   */
  String getTitle();
  /**
   * <code>optional string title = 4;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>optional string url = 5;</code>
   */
  boolean hasUrl();
  /**
   * <code>optional string url = 5;</code>
   */
  String getUrl();
  /**
   * <code>optional string url = 5;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>repeated string snippet = 6;</code>
   */
  com.google.protobuf.ProtocolStringList
      getSnippetList();
  /**
   * <code>repeated string snippet = 6;</code>
   */
  int getSnippetCount();
  /**
   * <code>repeated string snippet = 6;</code>
   */
  String getSnippet(int index);
  /**
   * <code>repeated string snippet = 6;</code>
   */
  com.google.protobuf.ByteString
      getSnippetBytes(int index);

  /**
   * <code>optional .Offer priceDeprecated = 7;</code>
   */
  boolean hasPriceDeprecated();
  /**
   * <code>optional .Offer priceDeprecated = 7;</code>
   */
  Offer getPriceDeprecated();
  /**
   * <code>optional .Offer priceDeprecated = 7;</code>
   */
  OfferOrBuilder getPriceDeprecatedOrBuilder();

  /**
   * <code>optional .Availability availability = 9;</code>
   */
  boolean hasAvailability();
  /**
   * <code>optional .Availability availability = 9;</code>
   */
  Availability getAvailability();
  /**
   * <code>optional .Availability availability = 9;</code>
   */
  AvailabilityOrBuilder getAvailabilityOrBuilder();

  /**
   * <code>repeated .Image image = 10;</code>
   */
  java.util.List<Image>
      getImageList();
  /**
   * <code>repeated .Image image = 10;</code>
   */
  Image getImage(int index);
  /**
   * <code>repeated .Image image = 10;</code>
   */
  int getImageCount();
  /**
   * <code>repeated .Image image = 10;</code>
   */
  java.util.List<? extends ImageOrBuilder>
      getImageOrBuilderList();
  /**
   * <code>repeated .Image image = 10;</code>
   */
  ImageOrBuilder getImageOrBuilder(int index);

  /**
   * <code>repeated .Document child = 11;</code>
   */
  java.util.List<Document>
      getChildList();
  /**
   * <code>repeated .Document child = 11;</code>
   */
  Document getChild(int index);
  /**
   * <code>repeated .Document child = 11;</code>
   */
  int getChildCount();
  /**
   * <code>repeated .Document child = 11;</code>
   */
  java.util.List<? extends DocumentOrBuilder>
      getChildOrBuilderList();
  /**
   * <code>repeated .Document child = 11;</code>
   */
  DocumentOrBuilder getChildOrBuilder(int index);

  /**
   * <code>optional .AggregateRating aggregateRating = 13;</code>
   */
  boolean hasAggregateRating();
  /**
   * <code>optional .AggregateRating aggregateRating = 13;</code>
   */
  AggregateRating getAggregateRating();
  /**
   * <code>optional .AggregateRating aggregateRating = 13;</code>
   */
  AggregateRatingOrBuilder getAggregateRatingOrBuilder();

  /**
   * <code>repeated .Offer offer = 14;</code>
   */
  java.util.List<Offer>
      getOfferList();
  /**
   * <code>repeated .Offer offer = 14;</code>
   */
  Offer getOffer(int index);
  /**
   * <code>repeated .Offer offer = 14;</code>
   */
  int getOfferCount();
  /**
   * <code>repeated .Offer offer = 14;</code>
   */
  java.util.List<? extends OfferOrBuilder>
      getOfferOrBuilderList();
  /**
   * <code>repeated .Offer offer = 14;</code>
   */
  OfferOrBuilder getOfferOrBuilder(int index);

  /**
   * <code>repeated .TranslatedText translatedSnippet = 15;</code>
   */
  java.util.List<com.thunderclouddev.playstoreapi.proto.TranslatedText>
      getTranslatedSnippetList();
  /**
   * <code>repeated .TranslatedText translatedSnippet = 15;</code>
   */
  com.thunderclouddev.playstoreapi.proto.TranslatedText getTranslatedSnippet(int index);
  /**
   * <code>repeated .TranslatedText translatedSnippet = 15;</code>
   */
  int getTranslatedSnippetCount();
  /**
   * <code>repeated .TranslatedText translatedSnippet = 15;</code>
   */
  java.util.List<? extends com.thunderclouddev.playstoreapi.proto.TranslatedTextOrBuilder>
      getTranslatedSnippetOrBuilderList();
  /**
   * <code>repeated .TranslatedText translatedSnippet = 15;</code>
   */
  com.thunderclouddev.playstoreapi.proto.TranslatedTextOrBuilder getTranslatedSnippetOrBuilder(
      int index);

  /**
   * <code>repeated .DocumentVariant documentVariant = 16;</code>
   */
  java.util.List<com.thunderclouddev.playstoreapi.proto.DocumentVariant>
      getDocumentVariantList();
  /**
   * <code>repeated .DocumentVariant documentVariant = 16;</code>
   */
  com.thunderclouddev.playstoreapi.proto.DocumentVariant getDocumentVariant(int index);
  /**
   * <code>repeated .DocumentVariant documentVariant = 16;</code>
   */
  int getDocumentVariantCount();
  /**
   * <code>repeated .DocumentVariant documentVariant = 16;</code>
   */
  java.util.List<? extends com.thunderclouddev.playstoreapi.proto.DocumentVariantOrBuilder>
      getDocumentVariantOrBuilderList();
  /**
   * <code>repeated .DocumentVariant documentVariant = 16;</code>
   */
  com.thunderclouddev.playstoreapi.proto.DocumentVariantOrBuilder getDocumentVariantOrBuilder(
      int index);

  /**
   * <code>repeated string categoryId = 17;</code>
   */
  com.google.protobuf.ProtocolStringList
      getCategoryIdList();
  /**
   * <code>repeated string categoryId = 17;</code>
   */
  int getCategoryIdCount();
  /**
   * <code>repeated string categoryId = 17;</code>
   */
  String getCategoryId(int index);
  /**
   * <code>repeated string categoryId = 17;</code>
   */
  com.google.protobuf.ByteString
      getCategoryIdBytes(int index);

  /**
   * <code>repeated .Document decoration = 18;</code>
   */
  java.util.List<Document>
      getDecorationList();
  /**
   * <code>repeated .Document decoration = 18;</code>
   */
  Document getDecoration(int index);
  /**
   * <code>repeated .Document decoration = 18;</code>
   */
  int getDecorationCount();
  /**
   * <code>repeated .Document decoration = 18;</code>
   */
  java.util.List<? extends DocumentOrBuilder>
      getDecorationOrBuilderList();
  /**
   * <code>repeated .Document decoration = 18;</code>
   */
  DocumentOrBuilder getDecorationOrBuilder(int index);

  /**
   * <code>repeated .Document parent = 19;</code>
   */
  java.util.List<Document>
      getParentList();
  /**
   * <code>repeated .Document parent = 19;</code>
   */
  Document getParent(int index);
  /**
   * <code>repeated .Document parent = 19;</code>
   */
  int getParentCount();
  /**
   * <code>repeated .Document parent = 19;</code>
   */
  java.util.List<? extends DocumentOrBuilder>
      getParentOrBuilderList();
  /**
   * <code>repeated .Document parent = 19;</code>
   */
  DocumentOrBuilder getParentOrBuilder(int index);

  /**
   * <code>optional string privacyPolicyUrl = 20;</code>
   */
  boolean hasPrivacyPolicyUrl();
  /**
   * <code>optional string privacyPolicyUrl = 20;</code>
   */
  String getPrivacyPolicyUrl();
  /**
   * <code>optional string privacyPolicyUrl = 20;</code>
   */
  com.google.protobuf.ByteString
      getPrivacyPolicyUrlBytes();
}
