/*
 * Copyright (c) 2017.
 * Distributed under the GNU GPLv3 by David Whitman.
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This source code is made available to help others learn. Please don't clone my app.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

public interface ImageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Image)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 imageType = 1;</code>
   */
  boolean hasImageType();
  /**
   * <code>optional int32 imageType = 1;</code>
   */
  int getImageType();

  /**
   * <code>optional group Dimension = 2 { ... }</code>
   */
  boolean hasDimension();
  /**
   * <code>optional group Dimension = 2 { ... }</code>
   */
  Image.Dimension getDimension();
  /**
   * <code>optional group Dimension = 2 { ... }</code>
   */
  Image.DimensionOrBuilder getDimensionOrBuilder();

  /**
   * <code>optional string imageUrl = 5;</code>
   */
  boolean hasImageUrl();
  /**
   * <code>optional string imageUrl = 5;</code>
   */
  String getImageUrl();
  /**
   * <code>optional string imageUrl = 5;</code>
   */
  com.google.protobuf.ByteString
      getImageUrlBytes();

  /**
   * <code>optional string altTextLocalized = 6;</code>
   */
  boolean hasAltTextLocalized();
  /**
   * <code>optional string altTextLocalized = 6;</code>
   */
  String getAltTextLocalized();
  /**
   * <code>optional string altTextLocalized = 6;</code>
   */
  com.google.protobuf.ByteString
      getAltTextLocalizedBytes();

  /**
   * <code>optional string secureUrl = 7;</code>
   */
  boolean hasSecureUrl();
  /**
   * <code>optional string secureUrl = 7;</code>
   */
  String getSecureUrl();
  /**
   * <code>optional string secureUrl = 7;</code>
   */
  com.google.protobuf.ByteString
      getSecureUrlBytes();

  /**
   * <code>optional int32 positionInSequence = 8;</code>
   */
  boolean hasPositionInSequence();
  /**
   * <code>optional int32 positionInSequence = 8;</code>
   */
  int getPositionInSequence();

  /**
   * <code>optional bool supportsFifeUrlOptions = 9;</code>
   */
  boolean hasSupportsFifeUrlOptions();
  /**
   * <code>optional bool supportsFifeUrlOptions = 9;</code>
   */
  boolean getSupportsFifeUrlOptions();

  /**
   * <code>optional group Citation = 10 { ... }</code>
   */
  boolean hasCitation();
  /**
   * <code>optional group Citation = 10 { ... }</code>
   */
  Image.Citation getCitation();
  /**
   * <code>optional group Citation = 10 { ... }</code>
   */
  Image.CitationOrBuilder getCitationOrBuilder();

  /**
   * <code>optional string color = 15;</code>
   */
  boolean hasColor();
  /**
   * <code>optional string color = 15;</code>
   */
  String getColor();
  /**
   * <code>optional string color = 15;</code>
   */
  com.google.protobuf.ByteString
      getColorBytes();
}
