/*
 * Copyright (c) 2017.
 * Distributed under the GNU GPLv3 by David Whitman.
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This source code is made available to help others learn. Please don't clone my app.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

public interface IpLayerAppStatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IpLayerAppStat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 packageKey = 1;</code>
   */
  boolean hasPackageKey();
  /**
   * <code>optional int32 packageKey = 1;</code>
   */
  int getPackageKey();

  /**
   * <code>optional int32 applicationTag = 2;</code>
   */
  boolean hasApplicationTag();
  /**
   * <code>optional int32 applicationTag = 2;</code>
   */
  int getApplicationTag();

  /**
   * <code>repeated .AppBucket ipLayerAppBucket = 3;</code>
   */
  java.util.List<AppBucket>
      getIpLayerAppBucketList();
  /**
   * <code>repeated .AppBucket ipLayerAppBucket = 3;</code>
   */
  AppBucket getIpLayerAppBucket(int index);
  /**
   * <code>repeated .AppBucket ipLayerAppBucket = 3;</code>
   */
  int getIpLayerAppBucketCount();
  /**
   * <code>repeated .AppBucket ipLayerAppBucket = 3;</code>
   */
  java.util.List<? extends AppBucketOrBuilder>
      getIpLayerAppBucketOrBuilderList();
  /**
   * <code>repeated .AppBucket ipLayerAppBucket = 3;</code>
   */
  AppBucketOrBuilder getIpLayerAppBucketOrBuilder(int index);
}
