/*
 * Copyright (c) 2017.
 * Distributed under the GNU GPLv3 by David Whitman.
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This source code is made available to help others learn. Please don't clone my app.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

/**
 * Protobuf type {@code IpLayerNetworkStat}
 */
public final class IpLayerNetworkStat extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:IpLayerNetworkStat)
    IpLayerNetworkStatOrBuilder {
  // Use IpLayerNetworkStat.newBuilder() to construct.
  private IpLayerNetworkStat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private IpLayerNetworkStat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final IpLayerNetworkStat defaultInstance;
  public static IpLayerNetworkStat getDefaultInstance() {
    return defaultInstance;
  }

  public IpLayerNetworkStat getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private IpLayerNetworkStat(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            networkDetails_ = bs;
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            type_ = input.readInt32();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              ipLayerNetworkBucket_ = new java.util.ArrayList<IpLayerNetworkBucket>();
              mutable_bitField0_ |= 0x00000004;
            }
            ipLayerNetworkBucket_.add(input.readMessage(IpLayerNetworkBucket.PARSER, extensionRegistry));
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              ipLayerAppStat_ = new java.util.ArrayList<IpLayerAppStat>();
              mutable_bitField0_ |= 0x00000008;
            }
            ipLayerAppStat_.add(input.readMessage(IpLayerAppStat.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        ipLayerNetworkBucket_ = java.util.Collections.unmodifiableList(ipLayerNetworkBucket_);
      }
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        ipLayerAppStat_ = java.util.Collections.unmodifiableList(ipLayerAppStat_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GooglePlay.internal_static_IpLayerNetworkStat_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GooglePlay.internal_static_IpLayerNetworkStat_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            IpLayerNetworkStat.class, Builder.class);
  }

  public static com.google.protobuf.Parser<IpLayerNetworkStat> PARSER =
      new com.google.protobuf.AbstractParser<IpLayerNetworkStat>() {
    public IpLayerNetworkStat parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new IpLayerNetworkStat(input, extensionRegistry);
    }
  };

  @Override
  public com.google.protobuf.Parser<IpLayerNetworkStat> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int NETWORKDETAILS_FIELD_NUMBER = 1;
  private Object networkDetails_;
  /**
   * <code>optional string networkDetails = 1;</code>
   */
  public boolean hasNetworkDetails() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string networkDetails = 1;</code>
   */
  public String getNetworkDetails() {
    Object ref = networkDetails_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        networkDetails_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string networkDetails = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNetworkDetailsBytes() {
    Object ref = networkDetails_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      networkDetails_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private int type_;
  /**
   * <code>optional int32 type = 2;</code>
   */
  public boolean hasType() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional int32 type = 2;</code>
   */
  public int getType() {
    return type_;
  }

  public static final int IPLAYERNETWORKBUCKET_FIELD_NUMBER = 3;
  private java.util.List<IpLayerNetworkBucket> ipLayerNetworkBucket_;
  /**
   * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
   */
  public java.util.List<IpLayerNetworkBucket> getIpLayerNetworkBucketList() {
    return ipLayerNetworkBucket_;
  }
  /**
   * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
   */
  public java.util.List<? extends IpLayerNetworkBucketOrBuilder>
      getIpLayerNetworkBucketOrBuilderList() {
    return ipLayerNetworkBucket_;
  }
  /**
   * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
   */
  public int getIpLayerNetworkBucketCount() {
    return ipLayerNetworkBucket_.size();
  }
  /**
   * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
   */
  public IpLayerNetworkBucket getIpLayerNetworkBucket(int index) {
    return ipLayerNetworkBucket_.get(index);
  }
  /**
   * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
   */
  public IpLayerNetworkBucketOrBuilder getIpLayerNetworkBucketOrBuilder(
      int index) {
    return ipLayerNetworkBucket_.get(index);
  }

  public static final int IPLAYERAPPSTAT_FIELD_NUMBER = 4;
  private java.util.List<IpLayerAppStat> ipLayerAppStat_;
  /**
   * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
   */
  public java.util.List<IpLayerAppStat> getIpLayerAppStatList() {
    return ipLayerAppStat_;
  }
  /**
   * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
   */
  public java.util.List<? extends IpLayerAppStatOrBuilder>
      getIpLayerAppStatOrBuilderList() {
    return ipLayerAppStat_;
  }
  /**
   * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
   */
  public int getIpLayerAppStatCount() {
    return ipLayerAppStat_.size();
  }
  /**
   * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
   */
  public IpLayerAppStat getIpLayerAppStat(int index) {
    return ipLayerAppStat_.get(index);
  }
  /**
   * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
   */
  public IpLayerAppStatOrBuilder getIpLayerAppStatOrBuilder(
      int index) {
    return ipLayerAppStat_.get(index);
  }

  private void initFields() {
    networkDetails_ = "";
    type_ = 0;
    ipLayerNetworkBucket_ = java.util.Collections.emptyList();
    ipLayerAppStat_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getNetworkDetailsBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, type_);
    }
    for (int i = 0; i < ipLayerNetworkBucket_.size(); i++) {
      output.writeMessage(3, ipLayerNetworkBucket_.get(i));
    }
    for (int i = 0; i < ipLayerAppStat_.size(); i++) {
      output.writeMessage(4, ipLayerAppStat_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getNetworkDetailsBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, type_);
    }
    for (int i = 0; i < ipLayerNetworkBucket_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, ipLayerNetworkBucket_.get(i));
    }
    for (int i = 0; i < ipLayerAppStat_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, ipLayerAppStat_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  protected Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static IpLayerNetworkStat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static IpLayerNetworkStat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static IpLayerNetworkStat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static IpLayerNetworkStat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static IpLayerNetworkStat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static IpLayerNetworkStat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static IpLayerNetworkStat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static IpLayerNetworkStat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static IpLayerNetworkStat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static IpLayerNetworkStat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(IpLayerNetworkStat prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code IpLayerNetworkStat}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:IpLayerNetworkStat)
      com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStatOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GooglePlay.internal_static_IpLayerNetworkStat_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GooglePlay.internal_static_IpLayerNetworkStat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IpLayerNetworkStat.class, Builder.class);
    }

    // Construct using com.thunderclouddev.playstoreapi.proto.IpLayerNetworkStat.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getIpLayerNetworkBucketFieldBuilder();
        getIpLayerAppStatFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      networkDetails_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      if (ipLayerNetworkBucketBuilder_ == null) {
        ipLayerNetworkBucket_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        ipLayerNetworkBucketBuilder_.clear();
      }
      if (ipLayerAppStatBuilder_ == null) {
        ipLayerAppStat_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        ipLayerAppStatBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GooglePlay.internal_static_IpLayerNetworkStat_descriptor;
    }

    public IpLayerNetworkStat getDefaultInstanceForType() {
      return IpLayerNetworkStat.getDefaultInstance();
    }

    public IpLayerNetworkStat build() {
      IpLayerNetworkStat result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public IpLayerNetworkStat buildPartial() {
      IpLayerNetworkStat result = new IpLayerNetworkStat(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.networkDetails_ = networkDetails_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.type_ = type_;
      if (ipLayerNetworkBucketBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          ipLayerNetworkBucket_ = java.util.Collections.unmodifiableList(ipLayerNetworkBucket_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.ipLayerNetworkBucket_ = ipLayerNetworkBucket_;
      } else {
        result.ipLayerNetworkBucket_ = ipLayerNetworkBucketBuilder_.build();
      }
      if (ipLayerAppStatBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          ipLayerAppStat_ = java.util.Collections.unmodifiableList(ipLayerAppStat_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.ipLayerAppStat_ = ipLayerAppStat_;
      } else {
        result.ipLayerAppStat_ = ipLayerAppStatBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof IpLayerNetworkStat) {
        return mergeFrom((IpLayerNetworkStat)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(IpLayerNetworkStat other) {
      if (other == IpLayerNetworkStat.getDefaultInstance()) return this;
      if (other.hasNetworkDetails()) {
        bitField0_ |= 0x00000001;
        networkDetails_ = other.networkDetails_;
        onChanged();
      }
      if (other.hasType()) {
        setType(other.getType());
      }
      if (ipLayerNetworkBucketBuilder_ == null) {
        if (!other.ipLayerNetworkBucket_.isEmpty()) {
          if (ipLayerNetworkBucket_.isEmpty()) {
            ipLayerNetworkBucket_ = other.ipLayerNetworkBucket_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureIpLayerNetworkBucketIsMutable();
            ipLayerNetworkBucket_.addAll(other.ipLayerNetworkBucket_);
          }
          onChanged();
        }
      } else {
        if (!other.ipLayerNetworkBucket_.isEmpty()) {
          if (ipLayerNetworkBucketBuilder_.isEmpty()) {
            ipLayerNetworkBucketBuilder_.dispose();
            ipLayerNetworkBucketBuilder_ = null;
            ipLayerNetworkBucket_ = other.ipLayerNetworkBucket_;
            bitField0_ = (bitField0_ & ~0x00000004);
            ipLayerNetworkBucketBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getIpLayerNetworkBucketFieldBuilder() : null;
          } else {
            ipLayerNetworkBucketBuilder_.addAllMessages(other.ipLayerNetworkBucket_);
          }
        }
      }
      if (ipLayerAppStatBuilder_ == null) {
        if (!other.ipLayerAppStat_.isEmpty()) {
          if (ipLayerAppStat_.isEmpty()) {
            ipLayerAppStat_ = other.ipLayerAppStat_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureIpLayerAppStatIsMutable();
            ipLayerAppStat_.addAll(other.ipLayerAppStat_);
          }
          onChanged();
        }
      } else {
        if (!other.ipLayerAppStat_.isEmpty()) {
          if (ipLayerAppStatBuilder_.isEmpty()) {
            ipLayerAppStatBuilder_.dispose();
            ipLayerAppStatBuilder_ = null;
            ipLayerAppStat_ = other.ipLayerAppStat_;
            bitField0_ = (bitField0_ & ~0x00000008);
            ipLayerAppStatBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getIpLayerAppStatFieldBuilder() : null;
          } else {
            ipLayerAppStatBuilder_.addAllMessages(other.ipLayerAppStat_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      IpLayerNetworkStat parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (IpLayerNetworkStat) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object networkDetails_ = "";
    /**
     * <code>optional string networkDetails = 1;</code>
     */
    public boolean hasNetworkDetails() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string networkDetails = 1;</code>
     */
    public String getNetworkDetails() {
      Object ref = networkDetails_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          networkDetails_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string networkDetails = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNetworkDetailsBytes() {
      Object ref = networkDetails_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        networkDetails_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string networkDetails = 1;</code>
     */
    public Builder setNetworkDetails(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      networkDetails_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string networkDetails = 1;</code>
     */
    public Builder clearNetworkDetails() {
      bitField0_ = (bitField0_ & ~0x00000001);
      networkDetails_ = getDefaultInstance().getNetworkDetails();
      onChanged();
      return this;
    }
    /**
     * <code>optional string networkDetails = 1;</code>
     */
    public Builder setNetworkDetailsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      networkDetails_ = value;
      onChanged();
      return this;
    }

    private int type_ ;
    /**
     * <code>optional int32 type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 type = 2;</code>
     */
    public int getType() {
      return type_;
    }
    /**
     * <code>optional int32 type = 2;</code>
     */
    public Builder setType(int value) {
      bitField0_ |= 0x00000002;
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 type = 2;</code>
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      type_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<IpLayerNetworkBucket> ipLayerNetworkBucket_ =
      java.util.Collections.emptyList();
    private void ensureIpLayerNetworkBucketIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        ipLayerNetworkBucket_ = new java.util.ArrayList<IpLayerNetworkBucket>(ipLayerNetworkBucket_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        IpLayerNetworkBucket, IpLayerNetworkBucket.Builder, IpLayerNetworkBucketOrBuilder> ipLayerNetworkBucketBuilder_;

    /**
     * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
     */
    public java.util.List<IpLayerNetworkBucket> getIpLayerNetworkBucketList() {
      if (ipLayerNetworkBucketBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ipLayerNetworkBucket_);
      } else {
        return ipLayerNetworkBucketBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
     */
    public int getIpLayerNetworkBucketCount() {
      if (ipLayerNetworkBucketBuilder_ == null) {
        return ipLayerNetworkBucket_.size();
      } else {
        return ipLayerNetworkBucketBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
     */
    public IpLayerNetworkBucket getIpLayerNetworkBucket(int index) {
      if (ipLayerNetworkBucketBuilder_ == null) {
        return ipLayerNetworkBucket_.get(index);
      } else {
        return ipLayerNetworkBucketBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
     */
    public Builder setIpLayerNetworkBucket(
        int index, IpLayerNetworkBucket value) {
      if (ipLayerNetworkBucketBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIpLayerNetworkBucketIsMutable();
        ipLayerNetworkBucket_.set(index, value);
        onChanged();
      } else {
        ipLayerNetworkBucketBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
     */
    public Builder setIpLayerNetworkBucket(
        int index, IpLayerNetworkBucket.Builder builderForValue) {
      if (ipLayerNetworkBucketBuilder_ == null) {
        ensureIpLayerNetworkBucketIsMutable();
        ipLayerNetworkBucket_.set(index, builderForValue.build());
        onChanged();
      } else {
        ipLayerNetworkBucketBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
     */
    public Builder addIpLayerNetworkBucket(IpLayerNetworkBucket value) {
      if (ipLayerNetworkBucketBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIpLayerNetworkBucketIsMutable();
        ipLayerNetworkBucket_.add(value);
        onChanged();
      } else {
        ipLayerNetworkBucketBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
     */
    public Builder addIpLayerNetworkBucket(
        int index, IpLayerNetworkBucket value) {
      if (ipLayerNetworkBucketBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIpLayerNetworkBucketIsMutable();
        ipLayerNetworkBucket_.add(index, value);
        onChanged();
      } else {
        ipLayerNetworkBucketBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
     */
    public Builder addIpLayerNetworkBucket(
        IpLayerNetworkBucket.Builder builderForValue) {
      if (ipLayerNetworkBucketBuilder_ == null) {
        ensureIpLayerNetworkBucketIsMutable();
        ipLayerNetworkBucket_.add(builderForValue.build());
        onChanged();
      } else {
        ipLayerNetworkBucketBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
     */
    public Builder addIpLayerNetworkBucket(
        int index, IpLayerNetworkBucket.Builder builderForValue) {
      if (ipLayerNetworkBucketBuilder_ == null) {
        ensureIpLayerNetworkBucketIsMutable();
        ipLayerNetworkBucket_.add(index, builderForValue.build());
        onChanged();
      } else {
        ipLayerNetworkBucketBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
     */
    public Builder addAllIpLayerNetworkBucket(
        Iterable<? extends IpLayerNetworkBucket> values) {
      if (ipLayerNetworkBucketBuilder_ == null) {
        ensureIpLayerNetworkBucketIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ipLayerNetworkBucket_);
        onChanged();
      } else {
        ipLayerNetworkBucketBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
     */
    public Builder clearIpLayerNetworkBucket() {
      if (ipLayerNetworkBucketBuilder_ == null) {
        ipLayerNetworkBucket_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        ipLayerNetworkBucketBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
     */
    public Builder removeIpLayerNetworkBucket(int index) {
      if (ipLayerNetworkBucketBuilder_ == null) {
        ensureIpLayerNetworkBucketIsMutable();
        ipLayerNetworkBucket_.remove(index);
        onChanged();
      } else {
        ipLayerNetworkBucketBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
     */
    public IpLayerNetworkBucket.Builder getIpLayerNetworkBucketBuilder(
        int index) {
      return getIpLayerNetworkBucketFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
     */
    public IpLayerNetworkBucketOrBuilder getIpLayerNetworkBucketOrBuilder(
        int index) {
      if (ipLayerNetworkBucketBuilder_ == null) {
        return ipLayerNetworkBucket_.get(index);  } else {
        return ipLayerNetworkBucketBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
     */
    public java.util.List<? extends IpLayerNetworkBucketOrBuilder>
         getIpLayerNetworkBucketOrBuilderList() {
      if (ipLayerNetworkBucketBuilder_ != null) {
        return ipLayerNetworkBucketBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ipLayerNetworkBucket_);
      }
    }
    /**
     * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
     */
    public IpLayerNetworkBucket.Builder addIpLayerNetworkBucketBuilder() {
      return getIpLayerNetworkBucketFieldBuilder().addBuilder(
          IpLayerNetworkBucket.getDefaultInstance());
    }
    /**
     * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
     */
    public IpLayerNetworkBucket.Builder addIpLayerNetworkBucketBuilder(
        int index) {
      return getIpLayerNetworkBucketFieldBuilder().addBuilder(
          index, IpLayerNetworkBucket.getDefaultInstance());
    }
    /**
     * <code>repeated .IpLayerNetworkBucket ipLayerNetworkBucket = 3;</code>
     */
    public java.util.List<IpLayerNetworkBucket.Builder>
         getIpLayerNetworkBucketBuilderList() {
      return getIpLayerNetworkBucketFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        IpLayerNetworkBucket, IpLayerNetworkBucket.Builder, IpLayerNetworkBucketOrBuilder>
        getIpLayerNetworkBucketFieldBuilder() {
      if (ipLayerNetworkBucketBuilder_ == null) {
        ipLayerNetworkBucketBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            IpLayerNetworkBucket, IpLayerNetworkBucket.Builder, IpLayerNetworkBucketOrBuilder>(
                ipLayerNetworkBucket_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        ipLayerNetworkBucket_ = null;
      }
      return ipLayerNetworkBucketBuilder_;
    }

    private java.util.List<IpLayerAppStat> ipLayerAppStat_ =
      java.util.Collections.emptyList();
    private void ensureIpLayerAppStatIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        ipLayerAppStat_ = new java.util.ArrayList<IpLayerAppStat>(ipLayerAppStat_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        IpLayerAppStat, IpLayerAppStat.Builder, IpLayerAppStatOrBuilder> ipLayerAppStatBuilder_;

    /**
     * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
     */
    public java.util.List<IpLayerAppStat> getIpLayerAppStatList() {
      if (ipLayerAppStatBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ipLayerAppStat_);
      } else {
        return ipLayerAppStatBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
     */
    public int getIpLayerAppStatCount() {
      if (ipLayerAppStatBuilder_ == null) {
        return ipLayerAppStat_.size();
      } else {
        return ipLayerAppStatBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
     */
    public IpLayerAppStat getIpLayerAppStat(int index) {
      if (ipLayerAppStatBuilder_ == null) {
        return ipLayerAppStat_.get(index);
      } else {
        return ipLayerAppStatBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
     */
    public Builder setIpLayerAppStat(
        int index, IpLayerAppStat value) {
      if (ipLayerAppStatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIpLayerAppStatIsMutable();
        ipLayerAppStat_.set(index, value);
        onChanged();
      } else {
        ipLayerAppStatBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
     */
    public Builder setIpLayerAppStat(
        int index, IpLayerAppStat.Builder builderForValue) {
      if (ipLayerAppStatBuilder_ == null) {
        ensureIpLayerAppStatIsMutable();
        ipLayerAppStat_.set(index, builderForValue.build());
        onChanged();
      } else {
        ipLayerAppStatBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
     */
    public Builder addIpLayerAppStat(IpLayerAppStat value) {
      if (ipLayerAppStatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIpLayerAppStatIsMutable();
        ipLayerAppStat_.add(value);
        onChanged();
      } else {
        ipLayerAppStatBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
     */
    public Builder addIpLayerAppStat(
        int index, IpLayerAppStat value) {
      if (ipLayerAppStatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIpLayerAppStatIsMutable();
        ipLayerAppStat_.add(index, value);
        onChanged();
      } else {
        ipLayerAppStatBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
     */
    public Builder addIpLayerAppStat(
        IpLayerAppStat.Builder builderForValue) {
      if (ipLayerAppStatBuilder_ == null) {
        ensureIpLayerAppStatIsMutable();
        ipLayerAppStat_.add(builderForValue.build());
        onChanged();
      } else {
        ipLayerAppStatBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
     */
    public Builder addIpLayerAppStat(
        int index, IpLayerAppStat.Builder builderForValue) {
      if (ipLayerAppStatBuilder_ == null) {
        ensureIpLayerAppStatIsMutable();
        ipLayerAppStat_.add(index, builderForValue.build());
        onChanged();
      } else {
        ipLayerAppStatBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
     */
    public Builder addAllIpLayerAppStat(
        Iterable<? extends IpLayerAppStat> values) {
      if (ipLayerAppStatBuilder_ == null) {
        ensureIpLayerAppStatIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ipLayerAppStat_);
        onChanged();
      } else {
        ipLayerAppStatBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
     */
    public Builder clearIpLayerAppStat() {
      if (ipLayerAppStatBuilder_ == null) {
        ipLayerAppStat_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        ipLayerAppStatBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
     */
    public Builder removeIpLayerAppStat(int index) {
      if (ipLayerAppStatBuilder_ == null) {
        ensureIpLayerAppStatIsMutable();
        ipLayerAppStat_.remove(index);
        onChanged();
      } else {
        ipLayerAppStatBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
     */
    public IpLayerAppStat.Builder getIpLayerAppStatBuilder(
        int index) {
      return getIpLayerAppStatFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
     */
    public IpLayerAppStatOrBuilder getIpLayerAppStatOrBuilder(
        int index) {
      if (ipLayerAppStatBuilder_ == null) {
        return ipLayerAppStat_.get(index);  } else {
        return ipLayerAppStatBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
     */
    public java.util.List<? extends IpLayerAppStatOrBuilder>
         getIpLayerAppStatOrBuilderList() {
      if (ipLayerAppStatBuilder_ != null) {
        return ipLayerAppStatBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ipLayerAppStat_);
      }
    }
    /**
     * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
     */
    public IpLayerAppStat.Builder addIpLayerAppStatBuilder() {
      return getIpLayerAppStatFieldBuilder().addBuilder(
          IpLayerAppStat.getDefaultInstance());
    }
    /**
     * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
     */
    public IpLayerAppStat.Builder addIpLayerAppStatBuilder(
        int index) {
      return getIpLayerAppStatFieldBuilder().addBuilder(
          index, IpLayerAppStat.getDefaultInstance());
    }
    /**
     * <code>repeated .IpLayerAppStat ipLayerAppStat = 4;</code>
     */
    public java.util.List<IpLayerAppStat.Builder>
         getIpLayerAppStatBuilderList() {
      return getIpLayerAppStatFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        IpLayerAppStat, IpLayerAppStat.Builder, IpLayerAppStatOrBuilder>
        getIpLayerAppStatFieldBuilder() {
      if (ipLayerAppStatBuilder_ == null) {
        ipLayerAppStatBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            IpLayerAppStat, IpLayerAppStat.Builder, IpLayerAppStatOrBuilder>(
                ipLayerAppStat_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        ipLayerAppStat_ = null;
      }
      return ipLayerAppStatBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:IpLayerNetworkStat)
  }

  static {
    defaultInstance = new IpLayerNetworkStat(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:IpLayerNetworkStat)
}

