/*
 * Copyright (c) 2017.
 * Distributed under the GNU GPLv3 by David Whitman.
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This source code is made available to help others learn. Please don't clone my app.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

public interface MusicDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MusicDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 censoring = 1;</code>
   */
  boolean hasCensoring();
  /**
   * <code>optional int32 censoring = 1;</code>
   */
  int getCensoring();

  /**
   * <code>optional int32 durationSec = 2;</code>
   */
  boolean hasDurationSec();
  /**
   * <code>optional int32 durationSec = 2;</code>
   */
  int getDurationSec();

  /**
   * <code>optional string originalReleaseDate = 3;</code>
   */
  boolean hasOriginalReleaseDate();
  /**
   * <code>optional string originalReleaseDate = 3;</code>
   */
  String getOriginalReleaseDate();
  /**
   * <code>optional string originalReleaseDate = 3;</code>
   */
  com.google.protobuf.ByteString
      getOriginalReleaseDateBytes();

  /**
   * <code>optional string label = 4;</code>
   */
  boolean hasLabel();
  /**
   * <code>optional string label = 4;</code>
   */
  String getLabel();
  /**
   * <code>optional string label = 4;</code>
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>repeated .ArtistDetails artist = 5;</code>
   */
  java.util.List<ArtistDetails>
      getArtistList();
  /**
   * <code>repeated .ArtistDetails artist = 5;</code>
   */
  ArtistDetails getArtist(int index);
  /**
   * <code>repeated .ArtistDetails artist = 5;</code>
   */
  int getArtistCount();
  /**
   * <code>repeated .ArtistDetails artist = 5;</code>
   */
  java.util.List<? extends ArtistDetailsOrBuilder>
      getArtistOrBuilderList();
  /**
   * <code>repeated .ArtistDetails artist = 5;</code>
   */
  ArtistDetailsOrBuilder getArtistOrBuilder(int index);

  /**
   * <code>repeated string genre = 6;</code>
   */
  com.google.protobuf.ProtocolStringList
      getGenreList();
  /**
   * <code>repeated string genre = 6;</code>
   */
  int getGenreCount();
  /**
   * <code>repeated string genre = 6;</code>
   */
  String getGenre(int index);
  /**
   * <code>repeated string genre = 6;</code>
   */
  com.google.protobuf.ByteString
      getGenreBytes(int index);

  /**
   * <code>optional string releaseDate = 7;</code>
   */
  boolean hasReleaseDate();
  /**
   * <code>optional string releaseDate = 7;</code>
   */
  String getReleaseDate();
  /**
   * <code>optional string releaseDate = 7;</code>
   */
  com.google.protobuf.ByteString
      getReleaseDateBytes();

  /**
   * <code>repeated int32 releaseType = 8;</code>
   */
  java.util.List<Integer> getReleaseTypeList();
  /**
   * <code>repeated int32 releaseType = 8;</code>
   */
  int getReleaseTypeCount();
  /**
   * <code>repeated int32 releaseType = 8;</code>
   */
  int getReleaseType(int index);
}
