/*
 * Copyright (c) 2017.
 * Distributed under the GNU GPLv3 by David Whitman.
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This source code is made available to help others learn. Please don't clone my app.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

/**
 * Protobuf type {@code PurchaseDeclinedData}
 */
public final class PurchaseDeclinedData extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PurchaseDeclinedData)
    PurchaseDeclinedDataOrBuilder {
  // Use PurchaseDeclinedData.newBuilder() to construct.
  private PurchaseDeclinedData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private PurchaseDeclinedData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final PurchaseDeclinedData defaultInstance;
  public static PurchaseDeclinedData getDefaultInstance() {
    return defaultInstance;
  }

  public PurchaseDeclinedData getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private PurchaseDeclinedData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            reason_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            showNotification_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GooglePlay.internal_static_PurchaseDeclinedData_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GooglePlay.internal_static_PurchaseDeclinedData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            PurchaseDeclinedData.class, Builder.class);
  }

  public static com.google.protobuf.Parser<PurchaseDeclinedData> PARSER =
      new com.google.protobuf.AbstractParser<PurchaseDeclinedData>() {
    public PurchaseDeclinedData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PurchaseDeclinedData(input, extensionRegistry);
    }
  };

  @Override
  public com.google.protobuf.Parser<PurchaseDeclinedData> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int REASON_FIELD_NUMBER = 1;
  private int reason_;
  /**
   * <code>optional int32 reason = 1;</code>
   */
  public boolean hasReason() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional int32 reason = 1;</code>
   */
  public int getReason() {
    return reason_;
  }

  public static final int SHOWNOTIFICATION_FIELD_NUMBER = 2;
  private boolean showNotification_;
  /**
   * <code>optional bool showNotification = 2;</code>
   */
  public boolean hasShowNotification() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional bool showNotification = 2;</code>
   */
  public boolean getShowNotification() {
    return showNotification_;
  }

  private void initFields() {
    reason_ = 0;
    showNotification_ = false;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, reason_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBool(2, showNotification_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, reason_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, showNotification_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  protected Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static PurchaseDeclinedData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PurchaseDeclinedData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PurchaseDeclinedData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PurchaseDeclinedData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PurchaseDeclinedData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static PurchaseDeclinedData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static PurchaseDeclinedData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static PurchaseDeclinedData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static PurchaseDeclinedData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static PurchaseDeclinedData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(PurchaseDeclinedData prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PurchaseDeclinedData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PurchaseDeclinedData)
      com.thunderclouddev.playstoreapi.proto.PurchaseDeclinedDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GooglePlay.internal_static_PurchaseDeclinedData_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GooglePlay.internal_static_PurchaseDeclinedData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PurchaseDeclinedData.class, Builder.class);
    }

    // Construct using com.thunderclouddev.playstoreapi.proto.PurchaseDeclinedData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      reason_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      showNotification_ = false;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GooglePlay.internal_static_PurchaseDeclinedData_descriptor;
    }

    public PurchaseDeclinedData getDefaultInstanceForType() {
      return PurchaseDeclinedData.getDefaultInstance();
    }

    public PurchaseDeclinedData build() {
      PurchaseDeclinedData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public PurchaseDeclinedData buildPartial() {
      PurchaseDeclinedData result = new PurchaseDeclinedData(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.reason_ = reason_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.showNotification_ = showNotification_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof PurchaseDeclinedData) {
        return mergeFrom((PurchaseDeclinedData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(PurchaseDeclinedData other) {
      if (other == PurchaseDeclinedData.getDefaultInstance()) return this;
      if (other.hasReason()) {
        setReason(other.getReason());
      }
      if (other.hasShowNotification()) {
        setShowNotification(other.getShowNotification());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      PurchaseDeclinedData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (PurchaseDeclinedData) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int reason_ ;
    /**
     * <code>optional int32 reason = 1;</code>
     */
    public boolean hasReason() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 reason = 1;</code>
     */
    public int getReason() {
      return reason_;
    }
    /**
     * <code>optional int32 reason = 1;</code>
     */
    public Builder setReason(int value) {
      bitField0_ |= 0x00000001;
      reason_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 reason = 1;</code>
     */
    public Builder clearReason() {
      bitField0_ = (bitField0_ & ~0x00000001);
      reason_ = 0;
      onChanged();
      return this;
    }

    private boolean showNotification_ ;
    /**
     * <code>optional bool showNotification = 2;</code>
     */
    public boolean hasShowNotification() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool showNotification = 2;</code>
     */
    public boolean getShowNotification() {
      return showNotification_;
    }
    /**
     * <code>optional bool showNotification = 2;</code>
     */
    public Builder setShowNotification(boolean value) {
      bitField0_ |= 0x00000002;
      showNotification_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool showNotification = 2;</code>
     */
    public Builder clearShowNotification() {
      bitField0_ = (bitField0_ & ~0x00000002);
      showNotification_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PurchaseDeclinedData)
  }

  static {
    defaultInstance = new PurchaseDeclinedData(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:PurchaseDeclinedData)
}

