/*
 * Copyright (c) 2017.
 * Distributed under the GNU GPLv3 by David Whitman.
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This source code is made available to help others learn. Please don't clone my app.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

public interface SearchResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string originalQuery = 1;</code>
   */
  boolean hasOriginalQuery();
  /**
   * <code>optional string originalQuery = 1;</code>
   */
  String getOriginalQuery();
  /**
   * <code>optional string originalQuery = 1;</code>
   */
  com.google.protobuf.ByteString
      getOriginalQueryBytes();

  /**
   * <code>optional string suggestedQuery = 2;</code>
   */
  boolean hasSuggestedQuery();
  /**
   * <code>optional string suggestedQuery = 2;</code>
   */
  String getSuggestedQuery();
  /**
   * <code>optional string suggestedQuery = 2;</code>
   */
  com.google.protobuf.ByteString
      getSuggestedQueryBytes();

  /**
   * <code>optional bool aggregateQuery = 3;</code>
   */
  boolean hasAggregateQuery();
  /**
   * <code>optional bool aggregateQuery = 3;</code>
   */
  boolean getAggregateQuery();

  /**
   * <code>repeated .Bucket bucket = 4;</code>
   */
  java.util.List<Bucket>
      getBucketList();
  /**
   * <code>repeated .Bucket bucket = 4;</code>
   */
  Bucket getBucket(int index);
  /**
   * <code>repeated .Bucket bucket = 4;</code>
   */
  int getBucketCount();
  /**
   * <code>repeated .Bucket bucket = 4;</code>
   */
  java.util.List<? extends BucketOrBuilder>
      getBucketOrBuilderList();
  /**
   * <code>repeated .Bucket bucket = 4;</code>
   */
  BucketOrBuilder getBucketOrBuilder(int index);

  /**
   * <code>repeated .DocV2 doc = 5;</code>
   */
  java.util.List<DocV2>
      getDocList();
  /**
   * <code>repeated .DocV2 doc = 5;</code>
   */
  DocV2 getDoc(int index);
  /**
   * <code>repeated .DocV2 doc = 5;</code>
   */
  int getDocCount();
  /**
   * <code>repeated .DocV2 doc = 5;</code>
   */
  java.util.List<? extends DocV2OrBuilder>
      getDocOrBuilderList();
  /**
   * <code>repeated .DocV2 doc = 5;</code>
   */
  DocV2OrBuilder getDocOrBuilder(int index);

  /**
   * <code>repeated .RelatedSearch relatedSearch = 6;</code>
   */
  java.util.List<RelatedSearch>
      getRelatedSearchList();
  /**
   * <code>repeated .RelatedSearch relatedSearch = 6;</code>
   */
  RelatedSearch getRelatedSearch(int index);
  /**
   * <code>repeated .RelatedSearch relatedSearch = 6;</code>
   */
  int getRelatedSearchCount();
  /**
   * <code>repeated .RelatedSearch relatedSearch = 6;</code>
   */
  java.util.List<? extends RelatedSearchOrBuilder>
      getRelatedSearchOrBuilderList();
  /**
   * <code>repeated .RelatedSearch relatedSearch = 6;</code>
   */
  RelatedSearchOrBuilder getRelatedSearchOrBuilder(int index);
}
