/*
 * Copyright (c) 2017.
 * Distributed under the GNU GPLv3 by David Whitman.
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This source code is made available to help others learn. Please don't clone my app.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

public interface SongDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SongDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   */
  String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional .MusicDetails details = 2;</code>
   */
  boolean hasDetails();
  /**
   * <code>optional .MusicDetails details = 2;</code>
   */
  MusicDetails getDetails();
  /**
   * <code>optional .MusicDetails details = 2;</code>
   */
  MusicDetailsOrBuilder getDetailsOrBuilder();

  /**
   * <code>optional string albumName = 3;</code>
   */
  boolean hasAlbumName();
  /**
   * <code>optional string albumName = 3;</code>
   */
  String getAlbumName();
  /**
   * <code>optional string albumName = 3;</code>
   */
  com.google.protobuf.ByteString
      getAlbumNameBytes();

  /**
   * <code>optional int32 trackNumber = 4;</code>
   */
  boolean hasTrackNumber();
  /**
   * <code>optional int32 trackNumber = 4;</code>
   */
  int getTrackNumber();

  /**
   * <code>optional string previewUrl = 5;</code>
   */
  boolean hasPreviewUrl();
  /**
   * <code>optional string previewUrl = 5;</code>
   */
  String getPreviewUrl();
  /**
   * <code>optional string previewUrl = 5;</code>
   */
  com.google.protobuf.ByteString
      getPreviewUrlBytes();

  /**
   * <code>optional .ArtistDetails displayArtist = 6;</code>
   */
  boolean hasDisplayArtist();
  /**
   * <code>optional .ArtistDetails displayArtist = 6;</code>
   */
  ArtistDetails getDisplayArtist();
  /**
   * <code>optional .ArtistDetails displayArtist = 6;</code>
   */
  ArtistDetailsOrBuilder getDisplayArtistOrBuilder();
}
