/*
 * Copyright (c) 2017.
 * Distributed under the GNU GPLv3 by David Whitman.
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This source code is made available to help others learn. Please don't clone my app.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

public interface TvEpisodeDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TvEpisodeDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string parentDetailsUrl = 1;</code>
   */
  boolean hasParentDetailsUrl();
  /**
   * <code>optional string parentDetailsUrl = 1;</code>
   */
  String getParentDetailsUrl();
  /**
   * <code>optional string parentDetailsUrl = 1;</code>
   */
  com.google.protobuf.ByteString
      getParentDetailsUrlBytes();

  /**
   * <code>optional int32 episodeIndex = 2;</code>
   */
  boolean hasEpisodeIndex();
  /**
   * <code>optional int32 episodeIndex = 2;</code>
   */
  int getEpisodeIndex();

  /**
   * <code>optional string releaseDate = 3;</code>
   */
  boolean hasReleaseDate();
  /**
   * <code>optional string releaseDate = 3;</code>
   */
  String getReleaseDate();
  /**
   * <code>optional string releaseDate = 3;</code>
   */
  com.google.protobuf.ByteString
      getReleaseDateBytes();
}
