/*
 * Copyright (c) 2017.
 * Distributed under the GNU GPLv3 by David Whitman.
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This source code is made available to help others learn. Please don't clone my app.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.thunderclouddev.playstoreapi.proto;

/**
 * Protobuf type {@code UserNotificationData}
 */
public final class UserNotificationData extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:UserNotificationData)
    UserNotificationDataOrBuilder {
  // Use UserNotificationData.newBuilder() to construct.
  private UserNotificationData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private UserNotificationData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final UserNotificationData defaultInstance;
  public static UserNotificationData getDefaultInstance() {
    return defaultInstance;
  }

  public UserNotificationData getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private UserNotificationData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            notificationTitle_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            notificationText_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            tickerText_ = bs;
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            dialogTitle_ = bs;
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            dialogText_ = bs;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GooglePlay.internal_static_UserNotificationData_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GooglePlay.internal_static_UserNotificationData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            UserNotificationData.class, Builder.class);
  }

  public static com.google.protobuf.Parser<UserNotificationData> PARSER =
      new com.google.protobuf.AbstractParser<UserNotificationData>() {
    public UserNotificationData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserNotificationData(input, extensionRegistry);
    }
  };

  @Override
  public com.google.protobuf.Parser<UserNotificationData> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int NOTIFICATIONTITLE_FIELD_NUMBER = 1;
  private Object notificationTitle_;
  /**
   * <code>optional string notificationTitle = 1;</code>
   */
  public boolean hasNotificationTitle() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string notificationTitle = 1;</code>
   */
  public String getNotificationTitle() {
    Object ref = notificationTitle_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        notificationTitle_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string notificationTitle = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNotificationTitleBytes() {
    Object ref = notificationTitle_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      notificationTitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOTIFICATIONTEXT_FIELD_NUMBER = 2;
  private Object notificationText_;
  /**
   * <code>optional string notificationText = 2;</code>
   */
  public boolean hasNotificationText() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string notificationText = 2;</code>
   */
  public String getNotificationText() {
    Object ref = notificationText_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        notificationText_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string notificationText = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNotificationTextBytes() {
    Object ref = notificationText_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      notificationText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TICKERTEXT_FIELD_NUMBER = 3;
  private Object tickerText_;
  /**
   * <code>optional string tickerText = 3;</code>
   */
  public boolean hasTickerText() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string tickerText = 3;</code>
   */
  public String getTickerText() {
    Object ref = tickerText_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        tickerText_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string tickerText = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTickerTextBytes() {
    Object ref = tickerText_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      tickerText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIALOGTITLE_FIELD_NUMBER = 4;
  private Object dialogTitle_;
  /**
   * <code>optional string dialogTitle = 4;</code>
   */
  public boolean hasDialogTitle() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional string dialogTitle = 4;</code>
   */
  public String getDialogTitle() {
    Object ref = dialogTitle_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        dialogTitle_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string dialogTitle = 4;</code>
   */
  public com.google.protobuf.ByteString
      getDialogTitleBytes() {
    Object ref = dialogTitle_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dialogTitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIALOGTEXT_FIELD_NUMBER = 5;
  private Object dialogText_;
  /**
   * <code>optional string dialogText = 5;</code>
   */
  public boolean hasDialogText() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional string dialogText = 5;</code>
   */
  public String getDialogText() {
    Object ref = dialogText_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        dialogText_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string dialogText = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDialogTextBytes() {
    Object ref = dialogText_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dialogText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private void initFields() {
    notificationTitle_ = "";
    notificationText_ = "";
    tickerText_ = "";
    dialogTitle_ = "";
    dialogText_ = "";
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getNotificationTitleBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getNotificationTextBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getTickerTextBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeBytes(4, getDialogTitleBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeBytes(5, getDialogTextBytes());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getNotificationTitleBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getNotificationTextBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getTickerTextBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, getDialogTitleBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, getDialogTextBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  protected Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static UserNotificationData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UserNotificationData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UserNotificationData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UserNotificationData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UserNotificationData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static UserNotificationData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static UserNotificationData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static UserNotificationData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static UserNotificationData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static UserNotificationData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(UserNotificationData prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UserNotificationData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UserNotificationData)
      com.thunderclouddev.playstoreapi.proto.UserNotificationDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GooglePlay.internal_static_UserNotificationData_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GooglePlay.internal_static_UserNotificationData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserNotificationData.class, Builder.class);
    }

    // Construct using com.thunderclouddev.playstoreapi.proto.UserNotificationData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      notificationTitle_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      notificationText_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      tickerText_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      dialogTitle_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      dialogText_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GooglePlay.internal_static_UserNotificationData_descriptor;
    }

    public UserNotificationData getDefaultInstanceForType() {
      return UserNotificationData.getDefaultInstance();
    }

    public UserNotificationData build() {
      UserNotificationData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public UserNotificationData buildPartial() {
      UserNotificationData result = new UserNotificationData(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.notificationTitle_ = notificationTitle_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.notificationText_ = notificationText_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.tickerText_ = tickerText_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.dialogTitle_ = dialogTitle_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.dialogText_ = dialogText_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof UserNotificationData) {
        return mergeFrom((UserNotificationData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(UserNotificationData other) {
      if (other == UserNotificationData.getDefaultInstance()) return this;
      if (other.hasNotificationTitle()) {
        bitField0_ |= 0x00000001;
        notificationTitle_ = other.notificationTitle_;
        onChanged();
      }
      if (other.hasNotificationText()) {
        bitField0_ |= 0x00000002;
        notificationText_ = other.notificationText_;
        onChanged();
      }
      if (other.hasTickerText()) {
        bitField0_ |= 0x00000004;
        tickerText_ = other.tickerText_;
        onChanged();
      }
      if (other.hasDialogTitle()) {
        bitField0_ |= 0x00000008;
        dialogTitle_ = other.dialogTitle_;
        onChanged();
      }
      if (other.hasDialogText()) {
        bitField0_ |= 0x00000010;
        dialogText_ = other.dialogText_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      UserNotificationData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (UserNotificationData) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object notificationTitle_ = "";
    /**
     * <code>optional string notificationTitle = 1;</code>
     */
    public boolean hasNotificationTitle() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string notificationTitle = 1;</code>
     */
    public String getNotificationTitle() {
      Object ref = notificationTitle_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          notificationTitle_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string notificationTitle = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNotificationTitleBytes() {
      Object ref = notificationTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        notificationTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string notificationTitle = 1;</code>
     */
    public Builder setNotificationTitle(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      notificationTitle_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string notificationTitle = 1;</code>
     */
    public Builder clearNotificationTitle() {
      bitField0_ = (bitField0_ & ~0x00000001);
      notificationTitle_ = getDefaultInstance().getNotificationTitle();
      onChanged();
      return this;
    }
    /**
     * <code>optional string notificationTitle = 1;</code>
     */
    public Builder setNotificationTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      notificationTitle_ = value;
      onChanged();
      return this;
    }

    private Object notificationText_ = "";
    /**
     * <code>optional string notificationText = 2;</code>
     */
    public boolean hasNotificationText() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string notificationText = 2;</code>
     */
    public String getNotificationText() {
      Object ref = notificationText_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          notificationText_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string notificationText = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNotificationTextBytes() {
      Object ref = notificationText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        notificationText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string notificationText = 2;</code>
     */
    public Builder setNotificationText(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      notificationText_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string notificationText = 2;</code>
     */
    public Builder clearNotificationText() {
      bitField0_ = (bitField0_ & ~0x00000002);
      notificationText_ = getDefaultInstance().getNotificationText();
      onChanged();
      return this;
    }
    /**
     * <code>optional string notificationText = 2;</code>
     */
    public Builder setNotificationTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      notificationText_ = value;
      onChanged();
      return this;
    }

    private Object tickerText_ = "";
    /**
     * <code>optional string tickerText = 3;</code>
     */
    public boolean hasTickerText() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string tickerText = 3;</code>
     */
    public String getTickerText() {
      Object ref = tickerText_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tickerText_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string tickerText = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTickerTextBytes() {
      Object ref = tickerText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tickerText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string tickerText = 3;</code>
     */
    public Builder setTickerText(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      tickerText_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string tickerText = 3;</code>
     */
    public Builder clearTickerText() {
      bitField0_ = (bitField0_ & ~0x00000004);
      tickerText_ = getDefaultInstance().getTickerText();
      onChanged();
      return this;
    }
    /**
     * <code>optional string tickerText = 3;</code>
     */
    public Builder setTickerTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      tickerText_ = value;
      onChanged();
      return this;
    }

    private Object dialogTitle_ = "";
    /**
     * <code>optional string dialogTitle = 4;</code>
     */
    public boolean hasDialogTitle() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string dialogTitle = 4;</code>
     */
    public String getDialogTitle() {
      Object ref = dialogTitle_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dialogTitle_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string dialogTitle = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDialogTitleBytes() {
      Object ref = dialogTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dialogTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string dialogTitle = 4;</code>
     */
    public Builder setDialogTitle(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      dialogTitle_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string dialogTitle = 4;</code>
     */
    public Builder clearDialogTitle() {
      bitField0_ = (bitField0_ & ~0x00000008);
      dialogTitle_ = getDefaultInstance().getDialogTitle();
      onChanged();
      return this;
    }
    /**
     * <code>optional string dialogTitle = 4;</code>
     */
    public Builder setDialogTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      dialogTitle_ = value;
      onChanged();
      return this;
    }

    private Object dialogText_ = "";
    /**
     * <code>optional string dialogText = 5;</code>
     */
    public boolean hasDialogText() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string dialogText = 5;</code>
     */
    public String getDialogText() {
      Object ref = dialogText_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dialogText_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string dialogText = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDialogTextBytes() {
      Object ref = dialogText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dialogText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string dialogText = 5;</code>
     */
    public Builder setDialogText(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      dialogText_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string dialogText = 5;</code>
     */
    public Builder clearDialogText() {
      bitField0_ = (bitField0_ & ~0x00000010);
      dialogText_ = getDefaultInstance().getDialogText();
      onChanged();
      return this;
    }
    /**
     * <code>optional string dialogText = 5;</code>
     */
    public Builder setDialogTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      dialogText_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:UserNotificationData)
  }

  static {
    defaultInstance = new UserNotificationData(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:UserNotificationData)
}

